const fs = require('fs');
const path = 'C:/Users/king/Desktop/kkk/gift-platform/client/src/pages/StorePage.jsx';
let full = fs.readFileSync(path, 'utf8');

// Extract the PRODUCTS array section only
const prodStart = full.indexOf('const PRODUCTS = [');
const prodEnd = full.indexOf('];', prodStart) + 2;
const before = full.substring(0, prodStart);
let products = full.substring(prodStart, prodEnd);
const after = full.substring(prodEnd);

// Translation map for Chinese product content
const map = [
  ['英寸', 'in'], ['寸', 'in'], ['磅', 'lbs'], ['瓦', 'W'], ['伏', 'V'],
  ['只装', ' Count'], ['件套', '-Piece Set'], ['个装', ' Pack'],
  ['加仑', 'Gal'], ['分钟', 'min'], ['英尺', 'ft'],
  ['不锈钢', 'Stainless Steel'], ['铝合金', 'Aluminum Alloy'],
  ['深碳化竹', 'Deep Carbonized Bamboo'],
  ['汁槽设计收集液体', 'with Juice Grooves'],
  ['配木质收纳支架', 'Includes Wood Stand'], ['易握手柄', 'Easy-Grip Handle'],
  ['环保健康', 'Eco-Friendly & Healthy'],
  ['切碎/螺旋/切丁/切片', 'Chop/Spiralize/Dice/Slice'],
  ['不锈钢刀片', 'Stainless Steel Blades'],
  ['可更换不锈钢', 'Replaceable Stainless Steel'],
  ['洗碗机安全', 'Dishwasher Safe'], ['手洗', 'Hand Wash'],
  ['保护套', 'Protective Case'], ['软胶舒适握持', 'Soft Grip'],
  ['连续进料', 'Continuous Feed'], ['商用级', 'Commercial Grade'],
  ['强劲马达', 'Powerful Motor'], ['法国品牌', 'French Brand'],
  ['工作灯', 'Work Light'], ['线束', 'Wiring Harness'],
  ['自动跟踪拍摄', 'AI Auto Tracking'], ['团队运动', 'Team Sports'],
  ['无需订阅', 'No Subscription Required'],
  ['起动机', 'Starter Motor'], ['原厂替换', 'OEM Replacement'],
  ['工程师验证', 'Engineer Validated'],
  ['汽车清洗', 'Car Wash Kit'], ['泡沫枪', 'Foam Cannon'],
  ['洗车液', 'Car Soap'], ['轮毂清洁剂', 'Wheel Cleaner'],
  ['内外饰清洁护理', 'Interior & Exterior Detailing'],
  ['电池充电维护器', 'Battery Charger/Maintainer'],
  ['智能电流控制', 'Smart Amperage Control'],
  ['过充和短路保护', 'Overcharge & Short Circuit Protection'],
  ['多辆车', 'Multiple Vehicles'],
  ['厨房用具', 'Kitchen Utensils'], ['硅胶头', 'Silicone Heads'],
  ['木质手柄', 'Wooden Handles'], ['食品安全', 'Food Safe'],
  ['电烤盘', 'Electric Griddle'], ['烧烤二合一', 'Grill Combo'],
  ['不粘涂层', 'Non-Stick Coating'],
  ['玻璃保鲜盒', 'Glass Food Containers'],
  ['密封盖', 'Airtight Lids'], ['冷冻室', 'Freezer'],
  ['内置Alexa', 'Alexa Built-in'], ['触摸屏', 'Touch Screen'],
  ['运动模式', 'Sport Modes'], ['心率', 'Heart Rate'],
  ['血氧', 'SpO2'], ['睡眠监测', 'Sleep Monitor'],
  ['方形', 'Square'], ['圆形', 'Round'],
  ['碗碟沥水架', 'Dish Drying Rack'], ['伸缩', 'Extendable'],
  ['餐具架', 'Cutlery Holder'], ['杯架', 'Cup Holder'],
  ['货箱盖', 'Tonneau Cover'], ['三折软盖', 'Tri-Fold Soft Cover'],
  ['扫把簸箕套装', 'Broom & Dustpan Set'], ['长柄', 'Long Handle'],
  ['直立设计', 'Upright Design'], ['刷毛', 'Bristles'],
  ['搅拌碗', 'Mixing Bowls'], ['盖子', 'Lids'], ['滤网', 'Colander'],
  ['蓝牙耳机', 'Bluetooth Headphones'], ['头戴式', 'Over-Ear'],
  ['游戏模式低延迟', 'Gaming Mode Low Latency'],
  ['自动感应皂液器', 'Automatic Soap Dispenser'],
  ['红外免接触', 'Touchless Infrared'],
  ['出液量可调', '5 Adjustable Levels'],
  ['厨房喷枪', 'Kitchen Torch'], ['可调火焰', 'Adjustable Flame'],
  ['安全锁', 'Safety Lock'],
  ['车牌框', 'License Plate Frame'], ['亚光', 'Matte'],
  ['便携音箱', 'Portable Speaker'],
  ['紧凑型SUV', 'Compact SUV'], ['双色车顶', 'Two-Tone Roof'],
  ['插座扩展器', 'Outlet Extender'], ['夜灯', 'Night Light'],
  ['电风扇', 'Pedestal Fan'], ['摆动', 'Oscillating'],
  ['可调高度', 'Adjustable Height'],
  ['单向窗贴膜', 'One-Way Window Film'], ['隔热', 'Heat Blocking'],
  ['全遮光窗帘', 'Full Blackout Curtains'],
  ['亚麻混纺', 'Linen Blend'],
  ['记忆棉坐垫', 'Memory Foam Seat Cushion'], ['办公椅', 'Office Chair'],
  ['塔扇', 'Tower Fan'], ['静音', 'Quiet'],
  ['遥控', 'Remote Control'],
  ['护肤精华', 'Facial Treatment Essence'], ['抗衰老', 'Anti-Aging'],
  ['改善肤质', 'Refines Texture'], ['淡斑', 'Dark Spots'],
  ['零食盒', 'Snack Box'], ['分隔', 'Compartment'],
  ['可叠加', 'Stackable'],
  ['面部精华', 'Face Serum'], ['透明质酸', 'Hyaluronic Acid'],
  ['密封袋', 'Storage Bags'], ['双层拉链', 'Double Zipper'],
  ['商务鞋', 'Business Shoes'], ['牛津鞋', 'Oxford'],
  ['零食拼盘', 'Snackle Box'], ['分隔托盘', 'Divided Serving Tray'],
  ['妆前乳', 'Makeup Primer'], ['无硅', 'Silicone-Free'],
  ['精华质地', 'Serum Texture'], ['光泽肌', 'Radiant Skin'],
  ['运动鞋', 'Sneakers'], ['系带', 'Lace-Up'],
  ['护肤套装', 'Skincare Gift Set'], ['野山参', 'Wild Ginseng'],
  ['正装', 'Full Size'],
  ['登山鞋', 'Hiking Shoes'], ['橡胶底', 'Rubber Sole'],
  ['旋转化妆收纳', 'Rotating Makeup Organizer'],
  ['化妆品展示架', 'Cosmetic Display Stand'],
  ['防滑工作鞋', 'Non-Slip Work Shoes'], ['一脚蹬', 'Slip-On'],
  ['厨房餐厅', 'Kitchen Restaurant'],
  ['女士步行鞋', 'Womens Sneakers'], ['透气', 'Breathable'],
  ['厚底乐福鞋', 'Platform Loafers'],
  ['儿童运动鞋', 'Kids Sneaker'],
  ['弹力绳', 'Bungee'], ['双效修复精华', 'Dual Recovery Serum'],
  ['防漏', 'Leak-Proof'], ['防刺穿', 'Puncture-Resistant'],
  ['防撕裂', 'Tear-Resistant'],
  ['持续除味', 'Continuous Odor Control'], ['台面式', 'Countertop'],
  ['均匀导热', 'Even Heat Distribution'], ['美国制造', 'Made in USA'],
  ['双天线前后', 'Dual Antennas Front/Rear'],
  ['方向指示', 'Directional Arrows'], ['语音提醒', 'Voice Alerts'],
  ['超远距离', 'Extreme Range'], ['全方位', '360 Degree'],
  ['红绿灯和测速摄像头提醒', 'Red Light & Speed Camera Alerts'],
  ['刹车/转向/尾灯', 'Brake/Turn/Tail Light'],
  ['防眩光', 'Anti-Glare'], ['触摸', 'Touch'],
  ['翻转触屏', 'Flip Touch Screen'],
  ['窄边框', 'NanoEdge'], ['翻新', 'Renewed'], ['解锁版', 'Unlocked'],
  ['认证翻新', 'Certified Refurbished'],
  ['免提POV', 'Hands-Free POV'], ['磁吸安装', 'Magnetic Mount'],
  ['宠物视角', 'Pet POV'], ['微型', 'Mini'],
  ['洗地机', 'Floor Washer'], ['高温蒸汽', 'High-Temp Steam'],
  ['自清洁烘干', 'Self-Cleaning & Drying'],
  ['扫拖一体', 'Vacuum & Mop'], ['自动集尘站', 'Auto-Empty Station'],
  ['宠物毛发克星', 'Pet Hair Hero'],
  ['泛光+聚光组合', 'Flood+Spot Combo'], ['超亮', 'Ultra Bright'],
  ['前置', 'Front'], ['后置', 'Rear'],
  ['蒸烤/空气炸/对流/脱水', 'Steam/Air Fry/Convection/Dehydrate'],
  ['外置可拆卸', 'External Removable'],
  ['双区独立温控', 'Dual-Zone Temp Control'],
  ['防漏/防刺穿/防撕裂', 'Leak/Puncture/Tear Proof'],
  ['标准花园水管', 'Standard Garden Hose'],
  ['全车', 'Full Vehicle'],
  ['防锈金属', 'Anti-Rust Metal'],
  ['弹性高腰', 'Elastic High Waist'], ['宽松', 'Loose Fit'],
  ['修身', 'Slim Fit'], ['加厚', 'Thickened'],
  ['超薄', 'Ultra-Thin'], ['柔软', 'Soft'],
  ['舒适', 'Comfortable'], ['耐磨', 'Durable'],
  ['轻便', 'Lightweight'], ['快干', 'Quick-Dry'],
  ['吸汗', 'Moisture-Wicking'],
  ['褶裥', 'Pleated'], ['A字裙', 'A-Line Skirt'],
  ['蓬松', 'Puffy'], ['蕾丝', 'Lace'],
  ['雪纺', 'Chiffon'], ['缎面', 'Satin'],
  ['棉质', 'Cotton'], ['羊毛', 'Wool'],
  ['亚麻', 'Linen'], ['聚酯', 'Polyester'],
  ['高腰', 'High Waist'], ['低腰', 'Low Waist'],
  ['中腰', 'Mid Waist'], ['松紧腰', 'Elastic Waist'],
  ['系带', 'Drawstring'], ['纽扣', 'Button'],
  ['拉链', 'Zipper'], ['口袋', 'Pockets'],
  ['长袖', 'Long Sleeve'], ['短袖', 'Short Sleeve'],
  ['无袖', 'Sleeveless'], ['七分袖', '3/4 Sleeve'],
  ['圆领', 'Crew Neck'], ['V领', 'V-Neck'],
  ['高领', 'Turtle Neck'], ['翻领', 'Lapel Collar'],
  ['连帽', 'Hooded'], ['印花', 'Print'],
  ['条纹', 'Stripe'], ['格子', 'Plaid'],
  ['纯色', 'Solid'], ['碎花', 'Floral'],
  ['迷彩', 'Camo'], ['豹纹', 'Leopard Print'],
  ['百褶裙', 'Pleated Skirt'], ['迷笛裙', 'Midi Skirt'],
  ['长裙', 'Maxi Skirt'], ['短裙', 'Mini Skirt'],
  ['半身裙', 'Skirt'], ['连衣裙', 'Dress'],
  ['连体裤', 'Jumpsuit'], ['阔腿裤', 'Wide Leg Pants'],
  ['紧身裤', 'Skinny Pants'], ['直筒裤', 'Straight Pants'],
  ['工装裤', 'Cargo Pants'], ['西装裤', 'Dress Pants'],
  ['卫衣', 'Hoodie'], ['T恤', 'T-Shirt'],
  ['衬衫', 'Shirt'], ['西装', 'Blazer'],
  ['夹克', 'Jacket'], ['大衣', 'Coat'],
  ['风衣', 'Trench Coat'], ['羽绒服', 'Down Jacket'],
  ['毛衣裙', 'Sweater Dress'], ['运动服', 'Tracksuit'],
  ['瑜伽', 'Yoga'], ['健身', 'Fitness'],
  ['沙滩', 'Beach'], ['泳装', 'Swimwear'],
  ['内衣', 'Underwear'], ['袜子', 'Socks'],
  ['腰带', 'Belt'], ['围巾', 'Scarf'],
  ['帽子', 'Hat'], ['手套', 'Gloves'],
  // Product descriptions - translate Chinese desc
  ['轻便Chromebook，适合学生和日常使用。14英寸屏，WiFi6，Type-C充电。', 'Lightweight Chromebook for students and daily use. 14\" display, WiFi 6, USB-C charging.'],
  ['HP OmniBook 3 新一代AI PC。Snapdragon X处理器，16GB高速内存，512GB固态硬盘。14英寸2K超清屏幕，轻薄便携。Windows 11 Home系统，AI智能助手。长续航，Type-C快充。', 'HP OmniBook 3 Next-Gen AI PC. Snapdragon X, 16GB RAM, 512GB SSD, 14\" 2K display, Windows 11 Home.'],
  ['ASUS ROG Astral RTX 5080 OC版旗舰显卡。16GB GDDR7高速显存，PCIe 5.0接口。4风扇设计+专利均热板散热。支持DLSS 4、光线追踪。', 'ASUS ROG Astral RTX 5080 OC Edition. 16GB GDDR7, PCIe 5.0, quad-fan cooling with vapor chamber. DLSS 4, ray tracing.'],
  ['ASUS ROG Astral RTX 5090 OC版旗舰显卡。32GB GDDR7超大显存，性能巅峰。4风扇+专利均热板散热。支持DLSS 4、光线追踪。4K/8K游戏无压力。', 'ASUS ROG Astral RTX 5090 OC Edition. 32GB GDDR7, peak performance, quad-fan vapor chamber. 4K/8K gaming ready.'],
  ['Meta Quest 3 512GB无线VR一体机。4K+超清显示，全彩透视混合现实。无需PC或线缆，开机即玩。100+款游戏，3个月Meta Horizon+会员。轻量化515g，长时间佩戴也舒适。', 'Meta Quest 3 512GB wireless VR headset. 4K+ display, full-color passthrough MR. No PC needed. 100+ games, 3-mo Meta Horizon+.'],
  ['Sony A7 IV全画幅微单相机。33MP Exmor R传感器，BIONZ XR处理器。4K 60p视频，759点高速对焦。5轴防抖，翻转屏。含28-70mm镜头，一机走天下。', 'Sony A7 IV full-frame mirrorless. 33MP Exmor R, BIONZ XR, 4K 60p, 759-point AF, 5-axis IBIS, flip screen. Includes 28-70mm lens.'],
  ['Sony A7 V全画幅微单旗舰。33MP堆栈式Exmor RS传感器，BIONZ XR2 AI处理器。30fps无黑视连拍，AI智能对焦。5轴防抖7.5档，4K120p视频。专业摄影首选。', 'Sony A7 V full-frame flagship. 33MP stacked Exmor RS, BIONZ XR2 AI, 30fps blackout-free burst, 5-axis 7.5-stop IBIS, 4K120p.'],
  ['Apple iPhone 17 Pro 256GB解锁版。A19 Pro芯片，48MP三摄系统。6.3寸ProMotion屏幕，5G网络。Cosmic Orange配色，Amazon Renewed Premium认证翻新。', 'Apple iPhone 17 Pro 256GB unlocked. A19 Pro, 48MP triple camera, 6.3\" ProMotion, 5G. Cosmic Orange. Amazon Renewed Premium.'],
  ['Apple Studio Display XDR 27寸5K显示器。5120x2880分辨率，1600nit峰值亮度。Thunderbolt 4接口，6扬声器空间音频。12MP超广角摄像头，人物居中功能。', 'Apple Studio Display XDR 27\" 5K monitor. 5120x2880, 1600nit peak. Thunderbolt 4, 6-speaker spatial audio, 12MP ultra-wide camera.'],
  ['LG 83英寸OLED evo G5旗舰。AI处理器，4K超清。Dolby全景声+视界。', 'LG 83\" OLED evo G5 flagship. AI processor, 4K. Dolby Atmos + Vision.'],
  ['Acer Chromebook Plus 515。15.6寸FHD触摸屏，Core i3处理器，8GB内存，256GB固态。Chrome OS系统，内置Google AI助手。WiFi 6E快速连接。', 'Acer Chromebook Plus 515. 15.6\" FHD touch, Core i3, 8GB RAM, 256GB SSD, Chrome OS with Google AI. WiFi 6E.'],
  ['ASUS Chromebook Flip CX1 14寸360度翻转触摸屏。NanoEdge窄边框，Celeron处理器，8GB内存。ChromeOS系统，平板/笔记本一键切换。', 'ASUS Chromebook Flip CX1 14\" 360° flip touch. NanoEdge, Celeron, 8GB RAM. ChromeOS, tablet/laptop switch.'],
  ['ASUS Chromebook CX15。15.6寸FHD防眩光大屏，Intel N50处理器，8GB内存。ChromeOS系统，Titan C2安全芯片。NanoEdge窄边框设计。', 'ASUS Chromebook CX15. 15.6\" FHD anti-glare, Intel N50, 8GB RAM. ChromeOS, Titan C2 security chip. NanoEdge design.'],
];

// Apply translations ONLY to the PRODUCTS section
for (const [zh, en] of map) {
  products = products.replaceAll(zh, en);
}

// Reassemble the file
const result = before + products + after;
fs.writeFileSync(path, result);
console.log('Product data translated successfully');
