// 生成 landing 越南语 locale（基于 landing en.json）
const fs = require('fs');
const path = require('path');
const en = require('../landing/src/i18n/locales/en.json');

const vi = {
  'app.name': 'Shopee Shopping Operations',
  'app.slogan': 'Nền tảng nhiệm vụ thương mại điện tử — Kết nối thị trường toàn cầu và kiếm tiền từ mỗi giao dịch',
  'app.cta_register': 'Tải App',
  'app.cta_download': 'Tải App',
  'app.cta_share': 'Chia sẻ',
  'app.cta_store': 'Mở trong App',
  'nav.home': 'Trang chủ',
  'nav.about': 'Giới thiệu',
  'nav.download': 'Tải xuống',
  'nav.store': 'Cửa hàng',
  'nav.faq': 'Câu hỏi',
  'hero.title': 'Amazon · Shopee · Lazada\nBạn quảng bá, chúng tôi hoàn thiện, bạn kiếm tiền',
  'hero.subtitle': 'Không tồn kho. Không vận chuyển. Không hỗ trợ khách hàng. Chọn nhiệm vụ thương mại điện tử trên Shopee Shopping Operations, quảng bá sản phẩm từ các sàn hàng đầu thế giới và bỏ túi lợi nhuận từ mỗi đơn hàng.',
  'hero.badge': '🔥 Kết nối 20+ nền tảng gồm Amazon, Shopee, Lazada, AliExpress',
  'stats.users': 'Người bán lại toàn cầu',
  'stats.gifts': 'Danh mục sản phẩm',
  'stats.invites': 'Đơn hàng mỗi ngày',
  'stats.volume': 'Tổng chi trả',
  'platforms.label': 'Kết nối thị trường toàn cầu',
  'platforms.title': 'Nhiệm vụ của bạn đến từ đơn hàng thật trên các nền tảng này',
  'platforms.desc': 'Chúng tôi tích hợp 20+ API thương mại điện tử toàn cầu — Amazon, Shopee, Lazada, AliExpress, TikTok Shop và nhiều hơn nữa. Mỗi nhiệm vụ đại diện cho một giao dịch thật. Bạn nhận lợi nhuận, chúng tôi lo chuỗi cung ứng và logistics.',
  'platforms.items.0.name': 'Amazon',
  'platforms.items.0.desc': 'Sàn lớn nhất thế giới, hơn 300 triệu khách hàng',
  'platforms.items.0.color': '#FF9900',
  'platforms.items.1.name': 'Shopee',
  'platforms.items.1.desc': 'Số 1 Đông Nam Á, hơn 700 triệu người dùng',
  'platforms.items.1.color': '#EE4D2D',
  'platforms.items.2.name': 'Lazada',
  'platforms.items.2.desc': '6 quốc gia trên khắp Đông Nam Á',
  'platforms.items.2.color': '#0F1470',
  'platforms.items.3.name': 'AliExpress',
  'platforms.items.3.desc': 'Nền tảng bán lẻ xuyên biên giới toàn cầu',
  'platforms.items.3.color': '#E62E04',
  'platforms.items.4.name': 'TikTok Shop',
  'platforms.items.4.desc': 'Thương mại xã hội tăng trưởng nhanh nhất',
  'platforms.items.4.color': '#000000',
  'platforms.items.5.name': 'eBay',
  'platforms.items.5.desc': 'Gã khổng lồ C2C toàn cầu',
  'platforms.items.5.color': '#0064D2',
  'value.label': 'Vì sao chọn Shopee Shopping Operations',
  'value.title': 'Kiếm lợi nhuận thương mại điện tử mà không cần là người bán',
  'value.desc': 'Thương mại điện tử truyền thống nghĩa là tìm nguồn hàng, tồn kho, vận hành, hỗ trợ và vận chuyển. Chúng tôi lo tất cả. Bạn chỉ cần chọn nhiệm vụ và chia sẻ liên kết — nhận hoa hồng từ mỗi đơn hàng.',
  'value.items.0.icon': 'Package',
  'value.items.0.title': 'Không tồn kho',
  'value.items.0.desc': 'Không hàng, không chi phí trả trước. Kết nối trực tiếp chuỗi cung ứng toàn cầu — bắt đầu với $0.',
  'value.items.1.icon': 'Truck',
  'value.items.1.title': 'Chúng tôi lo logistics',
  'value.items.1.desc': 'Amazon FBA, Shopee Xpress và các đối tác vận chuyển tự động hoàn thiện mọi đơn hàng.',
  'value.items.2.icon': 'Headphones',
  'value.items.2.title': 'Không hỗ trợ khách hàng',
  'value.items.2.desc': 'Hậu mãi do nền tảng và thương hiệu xử lý. Bạn chỉ tập trung quảng bá.',
  'value.items.3.icon': 'TrendingUp',
  'value.items.3.title': 'Lợi nhuận minh bạch',
  'value.items.3.desc': 'Giá vốn, giá thị trường, lợi nhuận của bạn — hiển thị rõ ràng. Thấy gì nhận nấy.',
  'how.label': 'Cách hoạt động',
  'how.title': 'Bắt đầu kiếm tiền chỉ với 3 bước đơn giản',
  'how.desc': 'Không cần kinh nghiệm. Đăng ký và bắt đầu kiếm tiền ngay.',
  'how.step1_title': 'Chọn nhiệm vụ',
  'how.step1_desc': 'Duyệt sản phẩm thịnh hành từ Amazon, Shopee, Lazada. Mỗi nhiệm vụ cho biết chính xác bạn kiếm được bao nhiêu mỗi đơn.',
  'how.step2_title': 'Chia sẻ liên kết',
  'how.step2_desc': 'Đăng liên kết sản phẩm trên Instagram, TikTok, WhatsApp, Telegram — bất cứ nơi nào có khán giả của bạn. Mỗi lượt chuyển đổi đều được tính.',
  'how.step3_title': 'Nhận lợi nhuận',
  'how.step3_desc': 'Khi đơn hàng hoàn tất, lợi nhuận tự động vào ví của bạn. Rút tiền bất cứ lúc nào, không phí ẩn.',
  'gifts.label': 'Nhiệm vụ thịnh hành',
  'gifts.title': 'Mỗi sản phẩm bạn quảng bá đều mang lại lợi nhuận',
  'gifts.desc': 'Từ điện tử đến đồ gia dụng — đội ngũ của chúng tôi thêm nhiệm vụ lợi nhuận cao mỗi ngày ở mọi danh mục.',
  'testimonials.label': 'Thu nhập thật',
  'testimonials.title': 'Họ đang kiếm tiền',
  'testimonials.desc': 'Thu nhập đã xác minh từ người bán lại toàn cầu.',
  'testimonials.items.0.name': 'Mike',
  'testimonials.items.0.role': 'Sinh viên · Bán thời gian · Mỹ',
  'testimonials.items.0.text': 'Đăng liên kết tai nghe Amazon trên Instagram và TikTok. Hơn 30 đơn trong tuần đầu, lợi nhuận $5-8 mỗi đơn. Kiếm $340 trong tháng đầu. Không lo vận chuyển — hoàn hảo cho sinh viên.',
  'testimonials.items.0.earned': '$340/tháng',
  'testimonials.items.1.name': 'Sarah',
  'testimonials.items.1.role': 'Mẹ nội trợ · Philippines',
  'testimonials.items.1.text': 'Chia sẻ sản phẩm em bé Shopee trong nhóm mẹ bỉm và WhatsApp. 30 phút mỗi ngày, kiếm $700+/tháng. Dễ hơn dropshipping nhiều — không tồn kho, không vận chuyển.',
  'testimonials.items.1.earned': '$720/tháng',
  'testimonials.items.2.name': 'Alex',
  'testimonials.items.2.role': 'Nhân viên văn phòng · Nghề tay trái · Malaysia',
  'testimonials.items.2.text': 'Tôi đăng ưu đãi công nghệ Lazada trên Telegram và Twitter khi đi làm và giờ nghỉ trưa. Giờ kiếm $1,250/tháng thu nhập thụ động đều đặn.',
  'testimonials.items.2.earned': '$1,250/tháng',
  'testimonials.items.3.name': 'Maria',
  'testimonials.items.3.role': 'Freelancer · Toàn thời gian · Brazil',
  'testimonials.items.3.text': 'Chạy video sản phẩm trên TikTok, Instagram Reels và YouTube Shorts. Xây dựng ma trận nội dung — giờ đạt $3,200/tháng, vượt cả công việc cũ.',
  'testimonials.items.3.earned': '$3,200/tháng',
  'store.label': 'Mua sắm',
  'store.title': 'Sản phẩm cao cấp, giá tốt',
  'store.desc': 'Dùng thu nhập để mua sắm — điện tử, làm đẹp, đồ gia dụng và hơn thế nữa.',
  'store.all': 'Tất cả',
  'store.digital': 'Điện tử',
  'store.women': 'Nữ',
  'store.men': 'Nam',
  'store.beauty': 'Làm đẹp',
  'store.shoes': 'Giày dép',
  'store.home': 'Nhà cửa',
  'store.accessories': 'Phụ kiện',
  'store.food': 'Thực phẩm',
  'store.toys': 'Đồ chơi',
  'store.sold': 'đã bán',
  'store.hot': 'Nổi bật',
  'store.searchPlaceholder': 'Tìm sản phẩm...',
  'store.products': 'sản phẩm',
  'store.noResults': 'Không tìm thấy sản phẩm phù hợp',
  'store.viewApp': 'Xem tất cả sản phẩm trong App →',
  'download.label': 'Tải xuống',
  'download.title': 'Kiếm tiền mọi lúc, mọi nơi',
  'download.desc': 'Tải app Shopee Shopping Operations để có trải nghiệm tốt nhất. Có sẵn cho Android.',
  'download.version': 'Phiên bản 1.0.0',
  'download.size': '~15MB',
  'download.features_title': 'Tính năng App',
  'download.features.0.icon': 'Zap',
  'download.features.0.title': 'Nhanh như chớp',
  'download.features.0.desc': 'Trải nghiệm native — nhanh và mượt hơn web di động',
  'download.features.1.icon': 'Bell',
  'download.features.1.title': 'Thông báo thời gian thực',
  'download.features.1.desc': 'Đẩy thông báo tức thì cho đơn hàng, hoa hồng và chi trả',
  'download.features.2.icon': 'Shield',
  'download.features.2.title': 'Bảo mật cấp ngân hàng',
  'download.features.2.desc': 'Truyền tải mã hóa, ví an toàn, xác thực đa yếu tố',
  'download.features.3.icon': 'Smartphone',
  'download.features.3.title': 'Chế độ ngoại tuyến',
  'download.features.3.desc': 'Xem nhiệm vụ và thu nhập ngay cả khi không có internet',
  'download.install_title': 'Hướng dẫn cài đặt',
  'download.install_steps.0.step': '1',
  'download.install_steps.0.title': 'Tải APK',
  'download.install_steps.0.desc': 'Chạm nút tải ở trên để lưu file APK',
  'download.install_steps.1.step': '2',
  'download.install_steps.1.title': 'Cho phép cài đặt',
  'download.install_steps.1.desc': 'Bật "Cài đặt từ nguồn không xác định" trong cài đặt thiết bị',
  'download.install_steps.2.step': '3',
  'download.install_steps.2.title': 'Cài đặt & Mở',
  'download.install_steps.2.desc': 'Mở APK, cài đặt, rồi đăng ký hoặc đăng nhập để bắt đầu kiếm tiền',
  'download.heroTitle': 'Bắt đầu giao dịch ngay',
  'download.heroDesc': 'Không cần tải — dùng trực tiếp trên trình duyệt. Ưu tiên di động, hoạt động mọi nơi.',
  'download.step1Title': 'Mở trong trình duyệt',
  'download.step1Desc': 'Hoạt động trên Chrome, Safari, Firefox — mọi thiết bị, mọi nền tảng.',
  'download.step2Title': 'Tạo tài khoản',
  'download.step2Desc': 'Đăng ký trong 30 giây với email và số điện thoại. Không chờ xác minh.',
  'download.step3Title': 'Bắt đầu kiếm tiền',
  'download.step3Desc': 'Nạp tiền, chọn sản phẩm, kiếm lợi nhuận. $5 đầu tiên miễn phí.',
  'download.ctaBtn': 'Mở App — Bắt đầu miễn phí',
  'download.ctaNote': 'Không cài đặt. Không APK. Chỉ cần mở và giao dịch.',
  'download.coming_soon': 'Sắp ra mắt',
  'download.apk_placeholder': 'File APK sắp có — hãy theo dõi!',
  'download.scanQr': 'Quét QR để tải',
  'download.downloadApk': 'Tải APK Android',
  'about.label': 'Về chúng tôi',
  'about.title': 'Kết nối thương mại điện tử toàn cầu, trao quyền cho mọi người kiếm tiền',
  'about.desc': 'Shopee Shopping Operations thành lập năm 2024 để phá bỏ rào cản tham gia thương mại điện tử. Không cần mở cửa hàng, không tồn kho, không vận chuyển — ai cũng có thể kiếm tiền từ giao dịch thương mại điện tử toàn cầu.',
  'about.mission_title': 'Sứ mệnh của chúng tôi',
  'about.mission': 'Tích hợp với Amazon, Shopee, Lazada và các sàn toàn cầu để biến mỗi giao dịch thành một nhiệm vụ — giúp người bình thường tham gia bùng nổ thương mại điện tử toàn cầu.',
  'about.vision_title': 'Tầm nhìn của chúng tôi',
  'about.vision': 'Trở thành nền tảng phân phối nhiệm vụ thương mại điện tử lớn nhất thế giới, kết nối 1 tỷ người dùng với thị trường toàn cầu và định nghĩa lại "làm thương mại điện tử".',
  'about.values_title': 'Giá trị cốt lõi',
  'about.values.0.title': 'Lợi nhuận minh bạch',
  'about.values.0.desc': 'Giá vốn và lợi nhuận của mỗi sản phẩm được công khai đầy đủ. Không bao giờ cắt phí ẩn.',
  'about.values.1.title': 'Không rào cản',
  'about.values.1.desc': 'Không cần kinh nghiệm. Không cần vốn. Chỉ cần đăng ký và bắt đầu.',
  'about.values.2.title': 'Sức mạnh nền tảng',
  'about.values.2.desc': 'Chuỗi cung ứng, logistics và hỗ trợ đều được xử lý. Bạn tập trung vào điều quan trọng — quảng bá.',
  'faq.label': 'Câu hỏi thường gặp',
  'faq.title': 'Có thắc mắc? Chúng tôi có câu trả lời',
  'faq.desc': 'Không tìm thấy điều cần? Liên hệ tại https://t.me/Shopping_Operations',
  'faq.searchPlaceholder': 'Tìm câu hỏi...',
  'faq.noResults': 'Không tìm thấy câu hỏi phù hợp',
  'faq.noResultsHint': 'Thử tìm kiếm hoặc danh mục khác',
  'faq.contactPrompt': 'Vẫn còn thắc mắc?',
  'faq.contactButton': 'Liên hệ hỗ trợ',
  'faq.categories.platform': 'Nền tảng',
  'faq.categories.earning': 'Thu nhập',
  'faq.categories.withdraw': 'Rút tiền',
  'faq.categories.invite': 'Giới thiệu',
  'faq.categories.tech': 'Kỹ thuật',
  'faq.items.0.q': 'Shopee Shopping Operations hoạt động với Amazon/Shopee thế nào?',
  'faq.items.0.a': 'Chúng tôi tích hợp 20+ nền tảng thương mại điện tử gồm Amazon, Shopee, Lazada và AliExpress. Mỗi nhiệm vụ trên Shopee Shopping Operations tương ứng với một listing sản phẩm thật. Bạn quảng bá sản phẩm — khi có đơn, bạn nhận lợi nhuận. Nền tảng và thương hiệu lo hoàn thiện và hỗ trợ.',
  'faq.items.0.cat': 'platform',
  'faq.items.1.q': 'Tôi có cần mua hàng tồn kho không?',
  'faq.items.1.a': 'Hoàn toàn không. Chúng tôi vận hành theo mô hình không tồn kho. Sản phẩm giao trực tiếp từ nền tảng và thương hiệu. Bạn không bao giờ chạm vào hàng — chỉ chọn nhiệm vụ và chia sẻ liên kết.',
  'faq.items.1.cat': 'platform',
  'faq.items.2.q': 'Shopee Shopping Operations có miễn phí không?',
  'faq.items.2.a': '100% miễn phí. Đăng ký, nhiệm vụ và quảng bá đều không mất phí. Chúng tôi chỉ lấy một khoản phí nền tảng nhỏ từ giao dịch thành công — bạn chỉ chia sẻ khi kiếm tiền.',
  'faq.items.2.cat': 'platform',
  'faq.items.3.q': 'Tôi kiếm tiền thế nào?',
  'faq.items.3.a': 'Ba cách: 1) Chọn nhiệm vụ thương mại điện tử — quảng bá sản phẩm Amazon/Shopee và nhận lợi nhuận chênh lệch giá; 2) Điểm danh hàng ngày và nhiệm vụ thưởng để nhận điểm; 3) Mời bạn bè và nhận hoa hồng đội đến 3 cấp.',
  'faq.items.3.cat': 'earning',
  'faq.items.4.q': 'Tôi kiếm được bao nhiêu mỗi đơn?',
  'faq.items.4.a': 'Tùy sản phẩm. Điện tử: $5-50 mỗi đơn. Đồ gia dụng: $3-15. Làm đẹp: $2-10. Giá vốn của chúng tôi là 85% giá thị trường — bạn giữ 15% lợi nhuận mỗi đơn.',
  'faq.items.4.cat': 'earning',
  'faq.items.5.q': 'Khi nào tôi được trả tiền?',
  'faq.items.5.a': 'Khi đơn được xác nhận đã giao (thường 3-7 ngày), lợi nhuận vào ví của bạn ngay lập tức. Rút tiền bất cứ lúc nào.',
  'faq.items.5.cat': 'earning',
  'faq.items.6.q': 'Làm thế nào để rút tiền?',
  'faq.items.6.a': 'Vào "Tài khoản của tôi" → "Ví" → "Rút tiền". Chúng tôi hỗ trợ chuyển khoản ngân hàng và ví điện tử. Rút tối thiểu $10, thường xử lý trong 1-3 ngày làm việc.',
  'faq.items.6.cat': 'withdraw',
  'faq.items.7.q': 'Có phí rút tiền không?',
  'faq.items.7.a': 'Người dùng thường chịu 1%. Thành viên VIP rút tiền miễn phí.',
  'faq.items.7.cat': 'withdraw',
  'faq.items.8.q': 'Làm thế nào để mời bạn bè?',
  'faq.items.8.a': 'Vào trang Nhiệm vụ, chạm "Mời bạn bè". Chia sẻ liên kết giới thiệu hoặc mã QR. Bạn nhận phần trăm thu nhập của họ đến 3 cấp sâu.',
  'faq.items.8.cat': 'invite',
  'faq.items.9.q': 'Có giới hạn lời mời không?',
  'faq.items.9.a': 'Không giới hạn. Mời nhiều = thu nhập đội nhiều.',
  'faq.items.9.cat': 'invite',
  'faq.items.10.q': 'Thiết bị nào được hỗ trợ?',
  'faq.items.10.a': 'App Android và web (H5) hiện có sẵn. Phiên bản iOS đang phát triển.',
  'faq.items.10.cat': 'tech',
  'faq.items.11.q': 'Dữ liệu của tôi có an toàn không?',
  'faq.items.11.a': 'Mã hóa cấp ngân hàng. Bản ghi giao dịch bất biến. Chúng tôi không bao giờ bán hoặc xâm phạm thông tin cá nhân của bạn.',
  'faq.items.11.cat': 'tech',
  'cta.title': 'Sẵn sàng kiếm tiền từ thương mại điện tử toàn cầu?',
  'cta.subtitle': 'Không tồn kho. Không vốn. Không rủi ro. Tải app và bắt đầu kiếm tiền hôm nay.',
  'cta.button': 'Tải App — Bắt đầu kiếm tiền',
  'footer.description': 'Shopee Shopping Operations — Kết nối thị trường toàn cầu, trao quyền cho mọi người kiếm tiền từ thương mại điện tử.',
  'footer.links': 'Liên kết nhanh',
  'footer.legal': 'Pháp lý',
  'footer.terms': 'Điều khoản dịch vụ',
  'footer.privacy': 'Chính sách bảo mật',
  'footer.contact': 'Liên hệ',
  'footer.email': '@Shopping_Operations',
  'footer.copyright': '© 2025 Shopee Shopping Operations. Bảo lưu mọi quyền.',
  'common.language': 'Ngôn ngữ',
  'common.darkMode': 'Chế độ tối',
  'common.lightMode': 'Chế độ sáng',
};

function build(obj, prefix = '') {
  const out = {};
  for (const k of Object.keys(obj)) {
    const key = prefix ? prefix + '.' + k : k;
    if (Array.isArray(obj[k])) {
      out[k] = obj[k].map((item, idx) => {
        const itemKey = key + '.' + idx;
        if (typeof item === 'object' && item !== null) {
          const sub = {};
          for (const sk of Object.keys(item)) {
            const subKey = itemKey + '.' + sk;
            sub[sk] = vi[subKey] !== undefined ? vi[subKey] : item[sk];
          }
          return sub;
        }
        return vi[itemKey] !== undefined ? vi[itemKey] : item;
      });
    } else if (typeof obj[k] === 'object' && obj[k] !== null) {
      out[k] = build(obj[k], key);
    } else {
      out[k] = vi[key] !== undefined ? vi[key] : obj[k];
    }
  }
  return out;
}

const viJson = build(en);
const outPath = path.join(__dirname, '..', 'landing', 'src', 'i18n', 'locales', 'vi.json');
fs.writeFileSync(outPath, JSON.stringify(viJson, null, 2) + '\n', 'utf8');
console.log('landing vi.json 已生成:', outPath);
