// 生成越南语 locale 文件 vi.json（基于 en.json 结构 + 内嵌越南语翻译）
const fs = require('fs');
const path = require('path');
const en = require('../client/src/i18n/locales/en.json');

// 扁平 key → 越南语翻译（完整 1048 条）
const vi = {
  'app.name': 'Shopee Shopping Operations',
  'app.slogan': 'Mời bạn bè, nhận thưởng tiền mặt',
  'app.loading': 'Đang tải...',
  'nav.home': 'Trang chủ',
  'nav.gifts': 'Quà tặng',
  'nav.tasks': 'Nhiệm vụ',
  'nav.invite': 'Mời bạn',
  'nav.rewards': 'Phần thưởng',
  'nav.mine': 'Cá nhân',
  'nav.admin': 'Quản trị',
  'nav.store': 'Cửa hàng',
  'auth.login': 'Đăng nhập',
  'auth.register': 'Đăng ký',
  'auth.logout': 'Đăng xuất',
  'auth.email': 'Email',
  'auth.phone': 'Số điện thoại',
  'auth.password': 'Mật khẩu',
  'auth.confirmPassword': 'Xác nhận mật khẩu',
  'auth.name': 'Biệt danh',
  'auth.referralCode': 'Mã giới thiệu',
  'auth.referralOptional': 'Tùy chọn',
  'auth.loginTitle': 'Đăng nhập',
  'auth.registerTitle': 'Tạo tài khoản',
  'auth.joinSlogan': 'Tham gia Shopee Shopping Operations, bắt đầu kiếm tiền ngay hôm nay',
  'auth.noAccount': 'Chưa có tài khoản?',
  'auth.hasAccount': 'Đã có tài khoản?',
  'auth.goRegister': 'Đăng ký',
  'auth.goLogin': 'Đăng nhập',
  'auth.loginBtn': 'Đăng nhập',
  'auth.registerBtn': 'Đăng ký',
  'auth.loggingIn': 'Đang đăng nhập...',
  'auth.registering': 'Đang đăng ký...',
  'auth.placeholderEmail': 'Nhập email của bạn',
  'auth.placeholderPhone': 'Nhập số điện thoại',
  'auth.placeholderPass': 'Nhập mật khẩu',
  'auth.placeholderConfirm': 'Xác nhận mật khẩu',
  'auth.placeholderName': 'Chọn biệt danh',
  'auth.placeholderReferral': 'Nhập mã giới thiệu nếu có',
  'auth.passMinLength': 'Mật khẩu phải có ít nhất 8 ký tự',
  'auth.passNotMatch': 'Mật khẩu không khớp',
  'auth.welcomeBack': 'Chào mừng trở lại',
  'auth.forgotPassword': 'Quên mật khẩu?',
  'auth.registerLink': 'Đăng ký →',
  'auth.loginLink': 'Đăng nhập →',
  'auth.completeProfile': 'Hoàn tất hồ sơ',
  'auth.startEarning': 'Bắt đầu kiếm tiền ngay hôm nay',
  'auth.justDetails': 'Chỉ vài thông tin nữa thôi',
  'auth.validEmail': 'Nhập email hợp lệ',
  'auth.validEmailPass': 'Vui lòng nhập email và mật khẩu hợp lệ',
  'auth.continueBtn': 'Tiếp tục',
  'auth.placeholderPassHint': 'Mật khẩu (8+ ký tự)',
  'auth.accountCreated': 'Tài khoản đã được tạo!',
  'auth.fillRequired': 'Vui lòng điền đầy đủ thông tin bắt buộc',
  'auth.loginSuccess': 'Đăng nhập thành công!',
  'auth.registerSuccess': 'Đăng ký thành công!',
  'auth.invalidCode': 'Mã giới thiệu không hợp lệ',
  'auth.resetTitle': 'Đặt lại mật khẩu',
  'auth.resetDesc': 'Xác minh email và số điện thoại để đặt mật khẩu mới',
  'auth.newPassword': 'Mật khẩu mới',
  'auth.placeholderNewPass': 'Nhập mật khẩu mới (tối thiểu 8 ký tự)',
  'auth.resetBtn': 'Đặt lại mật khẩu',
  'auth.resetDone': 'Đặt lại mật khẩu thành công',
  'auth.resetDoneDesc': 'Vui lòng đăng nhập bằng mật khẩu mới',
  'auth.resetFailed': 'Đặt lại mật khẩu thất bại',
  'gifts.title': 'Danh mục quà tặng',
  'gifts.effectiveInvites': 'Lời mời hợp lệ',
  'gifts.nextGoal': 'Mục tiêu tiếp theo',
  'gifts.needMore': 'Cần',
  'gifts.peopleToGet': 'thêm lời mời để nhận $',
  'gifts.allDone': '🎉 Chúc mừng! Đã mở khóa tất cả quà tặng!',
  'gifts.cash': 'Thưởng tiền mặt',
  'gifts.physical': 'Quà hiện vật',
  'gifts.virtual': 'Quà ảo',
  'gifts.claimable': 'Có sẵn',
  'gifts.needInvite': 'Mời',
  'gifts.people': '',
  'gifts.remaining': 'Còn lại',
  'gifts.copies': '',
  'gifts.claimNow': 'Nhận ngay',
  'gifts.kycNotice': 'Yêu cầu xác minh KYC',
  'gifts.kycNoticeDesc': 'Bạn bè được mời phải hoàn tất xác minh danh tính (KYC). Chỉ những xác minh được phê duyệt mới được tính là giới thiệu hợp lệ. Lời mời chưa hoàn tất KYC sẽ không đủ điều kiện nhận thưởng. Hãy đảm bảo bạn mời người dùng thật.',
  'gifts.kycStep1': 'Đăng ký tài khoản',
  'gifts.kycStep2': 'Nhập mã giới thiệu của bạn',
  'gifts.kycStep3': 'Vào Hồ sơ → Xác minh KYC để gửi giấy tờ',
  'gifts.kycStep4': 'Sau khi được phê duyệt, lời mời trở nên hợp lệ',
  'gifts.kycStepsTitle': 'Các bước bạn của bạn phải hoàn thành',
  'gifts.kycEffectiveInvites': 'Lời mời hợp lệ (Đã xác minh KYC)',
  'gifts.claiming': 'Đang nhận...',
  'gifts.cantClaim': 'Cần',
  'gifts.close': 'Đóng',
  'gifts.detail': 'Chi tiết',
  'gifts.required': 'Lời mời yêu cầu',
  'gifts.value': 'Giá trị',
  'gifts.claimed': 'Đã nhận',
  'gifts.available': 'Có sẵn',
  'gifts.status': 'Trạng thái',
  'gifts.claimDetail': 'Chi tiết nhận thưởng',
  'gifts.claimTime': 'Thời gian nhận',
  'gifts.deliverTime': 'Thời gian giao',
  'gifts.adminNote': 'Ghi chú quản trị',
  'gifts.giftType': 'Loại quà tặng',
  'tasks.title': 'Trung tâm nhiệm vụ',
  'tasks.checkin': 'Điểm danh hàng ngày',
  'tasks.streak': 'Chuỗi',
  'tasks.checkinNow': 'Điểm danh',
  'tasks.checkedIn': 'Đã điểm danh hôm nay',
  'tasks.checkinDone': 'Đã điểm danh!',
  'tasks.watchAd': 'Xem quảng cáo',
  'tasks.watchAdDesc': 'Xem quảng cáo 30 giây để nhận thưởng, tối đa 3 lần/ngày',
  'tasks.watchAdNow': 'Xem quảng cáo',
  'tasks.adWatching': 'Đang phát quảng cáo...',
  'tasks.adReward': 'Đã nhận thưởng quảng cáo',
  'tasks.adDone': 'Đã xem hết quảng cáo hôm nay',
  'tasks.milestones': 'Mốc mời bạn',
  'tasks.inviteProgress': 'Tiến độ mời bạn',
  'tasks.totalInvites': 'Tổng',
  'tasks.directInvites': 'Trực tiếp',
  'tasks.level1': 'Cấp 1',
  'tasks.level2': 'Cấp 2',
  'tasks.level3': 'Cấp 3',
  'tasks.recentInvitees': 'Người được mời gần đây',
  'tasks.noInvitees': 'Chưa có người được mời',
  'tasks.noInviteesHint': 'Chia sẻ link mời của bạn để bắt đầu!',
  'tasks.level': 'Cấp',
  'tasks.day': 'Ngày',
  'tasks.days': 'Ngày',
  'tasks.reward': 'Phần thưởng',
  'tasks.remaining': 'Còn lại',
  'tasks.done': 'Hoàn thành',
  'invite.invitedCount': 'Đã mời',
  'invite.effectiveStats': 'Hợp lệ',
  'invite.totalStats': 'Tổng',
  'invite.myCode': 'Mã giới thiệu của tôi',
  'invite.copy': 'Sao chép',
  'invite.shareLink': 'Chia sẻ liên kết',
  'invite.copyLink': 'Sao chép liên kết',
  'invite.qrCode': 'Mã QR',
  'invite.qrGenerating': 'Đang tạo mã QR...',
  'invite.qrHint': 'Cho bạn bè quét hoặc chụp màn hình để chia sẻ',
  'invite.shareTips': 'Mẹo chia sẻ',
  'invite.tip1': 'Sao chép liên kết và chia sẻ với bạn bè trên mạng xã hội',
  'invite.tip2': 'Chụp màn hình mã QR và đăng để bạn bè quét',
  'invite.tip3': 'Khi bạn bè đăng ký bằng mã của bạn, họ được tính là lời mời của bạn',
  'invite.tip4': 'Bạn cũng nhận thưởng khi người được mời mời thêm người khác!',
  'invite.copied': 'Đã sao chép!',
  'invite.codeCopied': 'Đã sao chép mã giới thiệu!',
  'invite.linkCopied': 'Đã sao chép liên kết chia sẻ!',
  'invite.title': 'Mời bạn bè',
  'invite.shareTitle': 'Chia sẻ liên kết của bạn',
  'invite.shareDesc': 'Chia sẻ liên kết này với bạn bè',
  'invite.copySuccess': 'Đã sao chép!',
  'invite.referralLink': 'Liên kết giới thiệu',
  'invite.scanToJoin': 'Quét để tham gia',
  'invite.howItWorks': 'Cách hoạt động',
  'invite.step1': 'Chia sẻ liên kết của bạn',
  'invite.step2': 'Bạn bè đăng ký',
  'invite.step3': 'Kiếm hoa hồng',
  'rewards.title': 'Lịch sử nhận thưởng',
  'rewards.totalEarned': 'Tổng đã kiếm',
  'rewards.claimRecords': 'lần nhận',
  'rewards.noRecords': 'Chưa có lần nhận nào',
  'rewards.noRecordsHint': 'Mời bạn bè và nhận thưởng tiền mặt khi đạt ngưỡng!',
  'rewards.claimTime': 'Thời gian nhận',
  'rewards.status': 'Trạng thái',
  'rewards.pendingRewards': 'Đang chờ',
  'rewards.claimedRewards': 'Đã nhận',
  'rewards.noRewards': 'Chưa có phần thưởng',
  'rewards.historyTitle': 'Lịch sử',
  'admin.title': 'Bảng quản trị',
  'admin.dashboard': 'Bảng điều khiển',
  'admin.userMgmt': 'Người dùng',
  'admin.giftMgmt': 'Quà tặng',
  'admin.claimMgmt': 'Yêu cầu nhận thưởng',
  'admin.totalUsers': 'Tổng người dùng',
  'admin.totalInvites': 'Tổng lời mời',
  'admin.pendingReview': 'Đang chờ',
  'admin.activeGifts': 'Quà tặng đang hoạt động',
  'admin.topInviters': 'Người mời hàng đầu',
  'admin.backToHome': 'Về trang chủ',
  'admin.search': 'Tìm kiếm',
  'admin.searchPlaceholder': 'Tìm email/điện thoại/tên...',
  'admin.prevPage': 'Trước',
  'admin.nextPage': 'Sau',
  'admin.addGift': '+ Thêm quà',
  'admin.editGift': 'Sửa quà',
  'admin.deactivate': 'Xóa',
  'admin.edit': 'Sửa',
  'admin.save': 'Lưu',
  'admin.create': 'Tạo quà',
  'admin.cancel': 'Hủy',
  'admin.confirmDeactivate': 'Bạn có chắc muốn vô hiệu quà tặng này?',
  'admin.all': 'Tất cả',
  'admin.approve': 'Phê duyệt',
  'admin.reject': 'Từ chối',
  'admin.detail': 'Chi tiết',
  'admin.close': 'Đóng',
  'admin.noData': 'Không có dữ liệu',
  'admin.giftForm': 'Biểu mẫu quà tặng',
  'admin.users': 'Người dùng',
  'admin.gifts': 'Quà tặng',
  'admin.claims': 'Yêu cầu nhận thưởng',
  'admin.withdrawals': 'Rút tiền',
  'admin.kyc': 'KYC',
  'admin.proofs': 'Bằng chứng',
  'admin.notifications': 'Thông báo',
  'admin.pending': 'Đang chờ',
  'admin.approved': 'Đã phê duyệt',
  'admin.rejected': 'Đã từ chối',
  'admin.completed': 'Đã hoàn thành',
  'admin.confirmApprove': 'Xác nhận?',
  'admin.confirmReject': 'Từ chối?',
  'admin.note': 'Ghi chú',
  'admin.totalGifts': 'Tổng quà tặng',
  'admin.totalClaims': 'Tổng yêu cầu nhận thưởng',
  'admin.totalWithdrawals': 'Tổng rút tiền',
  'giftData.新人红包.name': 'Thưởng người mới',
  'giftData.新人红包.desc': 'Mời 1 người bạn để nhận thưởng người mới này',
  'giftData.初级红包.name': 'Thưởng Đồng',
  'giftData.初级红包.desc': 'Mời 5 người bạn - bạn đang bắt đầu!',
  'giftData.中级红包.name': 'Thưởng Bạc',
  'giftData.中级红包.desc': 'Mời 15 người bạn - tiếp tục đà phát triển!',
  'giftData.高级红包.name': 'Thưởng Vàng',
  'giftData.高级红包.desc': 'Mời 50 người bạn - đẳng cấp thực thụ!',
  'giftData.顶级红包.name': 'Thưởng Kim cương',
  'giftData.顶级红包.desc': 'Mời 150 người bạn - đạt đẳng cấp tinh hoa!',
  'giftData.至尊大奖.name': 'Giải độc đắc huyền thoại',
  'giftData.至尊大奖.desc': 'Mời 500 người bạn - đẳng cấp huyền thoại!',
  'home.searchPlaceholder': 'Tìm kiếm sản phẩm...',
  'home.balance': 'Số dư',
  'home.todayProfit': 'Lợi nhuận hôm nay',
  'home.deposit': 'Tiền ký quỹ',
  'home.dailyFreeOrders': 'Đơn miễn phí hàng ngày',
  'home.grabProducts': 'Lấy sản phẩm, kiếm lợi nhuận',
  'home.grabSubtitle': '5 đơn miễn phí trọn đời · Lợi nhuận tới 25% mỗi món · Không cần ký quỹ',
  'home.grabAvailable': '{n} lượt lấy có sẵn tuần này',
  'home.grabNow': 'Lấy ngay',
  'home.quickDeposit': 'Nạp tiền',
  'home.quickWithdraw': 'Rút tiền',
  'home.quickStore': 'Cửa hàng của tôi',
  'home.quickTeam': 'Đội của tôi',
  'home.freeOrders': 'Đơn miễn phí',
  'home.freeLeft': '{n}/5 trọn đời',
  'home.freeEmpty': 'Không có sản phẩm miễn phí. Hãy quay lại sau.',
  'home.grab': 'Lấy',
  'home.claimed': 'Đã nhận',
  'home.activeHoldings': 'Đang nắm giữ',
  'home.viewAll': 'Xem tất cả',
  'home.noHoldings': 'Chưa có khoản nắm giữ nào',
  'home.startTrading': 'Bắt đầu giao dịch',
  'home.ordersProgress': '{done} / {total} đơn',
  'home.ordersToNext': '{n} đến cấp 2',
  'home.maxTier': 'Đã đạt cấp tối đa!',
  'home.inviteTitle': 'Mời bạn bè · Kiếm hoa hồng',
  'home.inviteDesc': '1.0% / 0.5% / 0.25% trên mỗi đơn',
  'home.inviteBtn': 'Mời',
  'home.copyCode': 'Mã: {code}',
  'home.copyLink': 'Sao chép liên kết',
  'home.myTeam': 'Đội của tôi',
  'home.members': '{n} thành viên',
  'home.verifications': 'Xác minh',
  'home.proofs': '{n} bằng chứng',
  'home.cost': 'Chi phí',
  'home.price': 'Giá',
  'home.dailyRate': 'Tỷ lệ hàng ngày',
  'home.status': 'Trạng thái',
  'home.noInviteCode': 'Không có mã mời',
  'home.noLink': 'Không có liên kết',
  'home.grabbed': 'Đã lấy {name}!',
  'home.grabFailed': 'Lấy thất bại',
  'home.storeLv': 'Cấp {n}',
  'mine.myCode': 'Mã giới thiệu của tôi',
  'mine.totalEarned': 'Tổng đã kiếm',
  'mine.directInvites': 'Lời mời trực tiếp',
  'mine.effectiveInvites': 'Lời mời hợp lệ',
  'mine.claimHistory': 'Lịch sử nhận thưởng',
  'mine.adminDesc': 'Quản lý người dùng và phê duyệt',
  'mine.adminPanel': 'Bảng quản trị',
  'mine.settings': 'Cài đặt',
  'mine.about': 'Giới thiệu',
  'mine.logout': 'Đăng xuất',
  'mine.logoutConfirm': 'Bạn có chắc muốn đăng xuất?',
  'mine.myTeam': 'Đội của tôi',
  'mine.myTeamDesc': 'Sơ đồ mời',
  'mine.myWallet': 'Ví',
  'mine.myWalletDesc': 'Thanh toán',
  'mine.messages': 'Hộp thư',
  'mine.messagesDesc': 'Thông báo & Trợ giúp',
  'mine.myStore': 'Thương mại điện tử',
  'mine.myStoreDesc': 'Xử lý đơn hàng & kiếm tiền',
  'mine.noWallet': 'Chưa có phương thức thanh toán',
  'mine.noWalletHint': 'Thêm tài khoản để nhận thưởng',
  'mine.bindAccount': 'Thêm tài khoản',
  'mine.help': 'Trợ giúp',
  'mine.helpBody': 'Mời bạn bè → đạt ngưỡng → nhận tiền mặt! Khi bạn bè mời thêm người, bạn nhận thêm thưởng. Liên hệ hỗ trợ nếu có thắc mắc.',
  'mine.title': 'Hồ sơ của tôi',
  'mine.security': 'Bảo mật',
  'mine.notifications': 'Thông báo',
  'mine.darkMode': 'Chế độ tối',
  'mine.darkModeHint': 'Chuyển giao diện',
  'mine.vipCenter': 'Trung tâm VIP',
  'mine.staking': 'Staking',
  'mine.withdraw': 'Rút tiền',
  'mine.verify': 'Xác minh',
  'mine.support': 'Hỗ trợ',
  'mine.kyc': 'KYC',
  'mine.legal': 'Pháp lý',
  'mine.profile': 'Hồ sơ',
  'mine.balance': 'Số dư',
  'mine.withdrawable': 'Có thể rút',
  'mine.locked': 'Đã khóa',
  'mine.available': 'Có sẵn',
  'team.title': 'Mời nhiều cấp hoạt động thế nào?',
  'team.level1Desc': 'Bạn bè bạn mời trực tiếp. Mỗi người tính là <strong>1.0</strong> lời mời hợp lệ',
  'team.level2Desc': 'Bạn bè do người được mời của bạn mời. Mỗi người tính <strong>0.5</strong> lời mời hợp lệ',
  'team.level3Desc': 'Bạn bè của người được mời cấp 2. Mỗi người tính <strong>0.25</strong> lời mời hợp lệ',
  'team.formula': '= {{l1}}×1.0 + {{l2}}×0.5 + {{l3}}×0.25',
  'team.tree': 'Sơ đồ mời',
  'team.joinedOn': 'Đã tham gia',
  'team.showRecent': 'Hiển thị {{shown}} trong {{total}}',
  'team.totalMembers': 'Tổng thành viên',
  'team.directInvites': 'Lời mời trực tiếp',
  'team.searchPlaceholder': 'Tìm thành viên...',
  'team.noMembers': 'Chưa có thành viên',
  'team.filterAll': 'Tất cả',
  'team.filterLevel1': 'Cấp 1',
  'team.filterLevel2': 'Cấp 2',
  'team.filterLevel3': 'Cấp 3',
  'team.joined': 'Đã tham gia',
  'team.commission': 'Hoa hồng',
  'wallet.crypto': 'Ví tiền mã hóa',
  'wallet.cryptoDesc': 'Liên kết địa chỉ ví tiền mã hóa của bạn. Phần thưởng sẽ được gửi dưới dạng <strong>USDT</strong> đến địa chỉ này. Hãy đảm bảo địa chỉ chính xác — giao dịch không thể hoàn tác.',
  'wallet.bound': 'Đã liên kết',
  'wallet.address': 'Địa chỉ ví',
  'wallet.changeBtn': 'Đổi',
  'wallet.unbind': 'Hủy liên kết',
  'wallet.unbindConfirm': 'Bạn có chắc muốn hủy liên kết?',
  'wallet.unbound': 'Đã hủy liên kết ví',
  'wallet.boundLabel': 'Ví đã liên kết',
  'wallet.transactions': 'Giao dịch',
  'wallet.noTransactions': 'Chưa có giao dịch',
  'wallet.deliveredLabel': 'Đã nhận',
  'wallet.pendingLabel': 'Đang xem xét',
  'wallet.rejectedLabel': 'Đã từ chối',
  'wallet.boundSuccess': 'Liên kết ví thành công',
  'wallet.selectNetwork': 'Chọn mạng',
  'wallet.enterAddress': 'Nhập địa chỉ ví {{chain}} của bạn',
  'wallet.warning': 'Kiểm tra kỹ địa chỉ — không thể khôi phục nếu gửi sai địa chỉ',
  'wallet.bindBtn': 'Liên kết ví',
  'wallet.saveChange': 'Lưu thay đổi',
  'wallet.replaceWallet': 'Đổi ví',
  'wallet.title': 'Ví',
  'wallet.network': 'Mạng',
  'wallet.bind': 'Liên kết ví',
  'wallet.noWallet': 'Chưa có ví',
  'wallet.bindFirst': 'Hãy liên kết ví trước',
  'wallet.totalDelivered': 'Tổng đã nhận',
  'wallet.totalPending': 'Tổng đang chờ',
  'wallet.totalEarned': 'Tổng đã kiếm',
  'messages.welcome': 'Chào mừng đến {{name}}!',
  'messages.welcomeBody': 'Mời bạn bè, xây dựng số lời mời hợp lệ và nhận thưởng tiền mặt. Khi bạn bè mời thêm người, bạn cũng nhận thưởng. Đây là cách bắt đầu:',
  'messages.guide': 'Bắt đầu',
  'messages.faq': 'Câu hỏi thường gặp',
  'messages.contact': 'Có thắc mắc? Liên hệ hỗ trợ',
  'messages.step1Title': 'Lấy liên kết mời của bạn',
  'messages.step1Body': 'Vào Nhiệm vụ để sao chép liên kết mời hoặc mã QR của bạn.',
  'messages.step2Title': 'Chia sẻ với bạn bè',
  'messages.step2Body': 'Gửi liên kết hoặc cho bạn bè quét mã QR để đăng ký.',
  'messages.step3Title': 'Bạn bè đăng ký',
  'messages.step3Body': 'Khi bạn bè đăng ký qua liên kết của bạn, họ trở thành lời mời cấp 1.',
  'messages.step4Title': 'Đạt ngưỡng',
  'messages.step4Body': 'Khi số lời mời hợp lệ đạt ngưỡng quà tặng, bạn có thể nhận thưởng.',
  'messages.step5Title': 'Thưởng nhiều cấp',
  'messages.step5Body': 'Khi người được mời của bạn mời thêm người, bạn nhận thưởng cấp 2 (×0.5) và cấp 3 (×0.25).',
  'messages.step6Title': 'Nhận thưởng của bạn',
  'messages.step6Body': 'Kiểm tra tiến độ trên trang Chủ hoặc Nhiệm vụ. Khi đủ điều kiện, chạm để nhận — thưởng sẽ được gửi đến ví tiền mã hóa của bạn.',
  'messages.faq1q': 'Làm thế nào để kiểm tra tiến độ mời bạn?',
  'messages.faq1a': 'Mở trang Nhiệm vụ để xem số lời mời hợp lệ và phân tích cấp.',
  'messages.faq2q': 'Vì sao số hợp lệ thấp hơn tổng lời mời?',
  'messages.faq2a': 'Lời mời hợp lệ = Cấp 1×1.0 + Cấp 2×0.5 + Cấp 3×0.25. Các cấp có trọng số khác nhau.',
  'messages.faq3q': 'Làm thế nào để liên kết ví?',
  'messages.faq3a': 'Vào Cá nhân → Ví, chọn mạng và nhập địa chỉ ví tiền mã hóa.',
  'messages.faq4q': 'Khi nào tôi nhận được thưởng?',
  'messages.faq4a': 'Sau khi nhận, quản trị viên sẽ xem xét và phê duyệt. Khi được phê duyệt, USDT sẽ được gửi đến ví đã liên kết.',
  'messages.faq5q': 'Mã giới thiệu của tôi ở đâu?',
  'messages.faq5a': 'Bạn có thể tìm mã giới thiệu trên trang Cá nhân, hoặc sao chép liên kết chia sẻ từ trang Nhiệm vụ.',
  'messages.title': 'Tin nhắn',
  'messages.welcomeMsg': 'Chào mừng!',
  'messages.quickQuestions': 'Câu hỏi nhanh',
  'messages.typePlaceholder': 'Nhập tin nhắn...',
  'messages.send': 'Gửi',
  'messages.online': 'Trực tuyến',
  'messages.offline': 'Ngoại tuyến',
  'stake.title': 'Gói Staking',
  'stake.active': 'Đang hoạt động',
  'stake.lockedAmount': 'Đã khóa',
  'stake.daysLeft': 'Ngày còn lại',
  'stake.profit': 'Lợi nhuận',
  'stake.boostInfo': 'Tăng x{{bonus}} · Quà cao cấp · Ưu tiên',
  'stake.multiplier': 'Hệ số',
  'stake.unstake': 'Mở khóa & Trả lại',
  'stake.forceUnstake': 'Hủy staking cưỡng bức (Demo)',
  'stake.unstakeConfirm': 'Hủy staking và nhận lại tiền ký quỹ?',
  'stake.forceUnstakeConfirm': 'Rút sớm phải chịu phạt thêm 20% (${{penalty}}). Toàn bộ ${{amount}} sẽ được trả lại. Tiếp tục?',
  'stake.unstakedPenalty': 'Đã hủy staking. Đã trả tiền ký quỹ. Vui lòng thanh toán ${{penalty}} phí phạt.',
  'stake.unstaked': 'Đã trả lại tiền ký quỹ',
  'stake.success': 'Staking thành công!',
  'stake.readyToUnlock': 'Sẵn sàng mở khóa — đã trả đủ tiền ký quỹ',
  'stake.unlocksIn': 'Mở khóa sau {{days}} ngày',
  'stake.choosePlan': 'Chọn gói Staking',
  'stake.premiumGifts': 'Đã mở khóa quà cao cấp',
  'stake.planbasic': 'Gói Cơ bản',
  'stake.planpro': 'Gói Pro',
  'stake.planmax': 'Gói Max',
  'stake.days': ' ngày',
  'stake.customTitle': 'Số tiền tùy chỉnh',
  'stake.customDesc': 'Bất kỳ số tiền nào, cùng 30% lợi nhuận',
  'stake.customPlaceholder': 'Tối thiểu $10',
  'stake.customAmount': 'Nhập số tiền',
  'stake.estimatedProfit': 'Lợi nhuận dự kiến',
  'stake.stakeNow': 'Stake ngay',
  'stake.confirmTitle': 'Xác nhận stake',
  'stake.confirm': 'Xác nhận',
  'stake.confirmDesc': 'Khóa ${{amount}} trong 30 ngày, nhận ~15% lợi nhuận (${{profit}}), tăng x{{bonus}} lời mời, trả đủ tiền ký quỹ',
  'stake.howItWorks': 'Cách hoạt động',
  'stake.availableBalance': 'Số dư khả dụng',
  'stake.insufficientBalance': 'Số dư không đủ! Cần ${{need}}, có ${{have}}',
  'stake.giftBasic1': 'Thưởng khởi đầu VIP',
  'stake.giftBasic2': 'Thưởng VIP Đồng',
  'stake.giftBasic3': 'Thưởng VIP Bạc',
  'stake.giftPro1': 'Thưởng khởi đầu PRO',
  'stake.giftPro2': 'Thưởng PRO Đồng',
  'stake.giftPro3': 'Thưởng PRO Bạc',
  'stake.giftPro4': 'Thưởng PRO Vàng',
  'stake.giftMax1': 'Thưởng khởi đầu MAX',
  'stake.giftMax2': 'Thưởng MAX Đồng',
  'stake.giftMax3': 'Thưởng MAX Bạc',
  'stake.giftMax4': 'Thưởng MAX Vàng',
  'stake.giftMax5': 'Thưởng MAX Kim cương',
  'stake.step1': 'Chọn gói và khóa tiền ký quỹ của bạn',
  'stake.step2': 'Trong thời gian khóa, hệ số mời tăng lên x1.5-3.0',
  'stake.step3': 'Mở khóa quà cao cấp độc quyền với ngưỡng thấp hơn',
  'stake.step4': 'Sau thời gian khóa, toàn bộ tiền ký quỹ được trả lại',
  'stake.myStake': 'Stake của tôi',
  'stake.stakingPlans': 'Gói',
  'stake.basic': 'Cơ bản',
  'stake.pro': 'Pro',
  'stake.max': 'Max',
  'stake.confirmBtn': 'Xác nhận',
  'stake.stakedSuccess': 'Đã stake!',
  'stake.unstakedSuccess': 'Đã hủy stake!',
  'stake.locked': 'Đã khóa',
  'stake.unlockDate': 'Ngày mở khóa',
  'stake.bonus': 'Thưởng',
  'stake.estimatedReturn': 'Lợi nhuận dự kiến',
  'stake.penalty': 'Phí phạt',
  'stake.noActiveStake': 'Không có stake đang hoạt động',
  'stake.activeStake': 'Stake đang hoạt động',
  'withdraw.title': 'Rút tiền',
  'withdraw.balance': 'Số dư khả dụng',
  'withdraw.pending': 'Đang chờ',
  'withdraw.totalWithdrawn': 'Tổng đã rút',
  'withdraw.withdrawNow': 'Rút ngay',
  'withdraw.to': 'Đến',
  'withdraw.amount': 'Số tiền',
  'withdraw.available': 'Khả dụng',
  'withdraw.submit': 'Xác nhận rút tiền',
  'withdraw.submitting': 'Đang xử lý...',
  'withdraw.hint': 'Rút tiền được xử lý trong vòng 24 giờ',
  'withdraw.noWallet': 'Hãy liên kết ví trước',
  'withdraw.bindFirst': 'Bạn cần liên kết ví tiền mã hóa trước khi rút tiền',
  'withdraw.minAmount': 'Số tiền rút tối thiểu là $20',
  'withdraw.minPlaceholder': 'Tối thiểu $20',
  'withdraw.invalidAmount': 'Nhập số tiền hợp lệ',
  'withdraw.insufficient': 'Số dư không đủ',
  'withdraw.success': 'Đã gửi yêu cầu rút tiền',
  'withdraw.cancelConfirm': 'Hủy yêu cầu rút tiền này?',
  'withdraw.cancelled': 'Đã hủy yêu cầu rút tiền',
  'withdraw.history': 'Lịch sử rút tiền',
  'withdraw.done': 'Đã hoàn thành',
  'withdraw.failed': 'Thất bại',
  'withdraw.submitWithdraw': 'Gửi',
  'withdraw.network': 'Mạng',
  'withdraw.address': 'Địa chỉ',
  'withdraw.time': 'Thời gian',
  'withdraw.status': 'Trạng thái',
  'vip.title': 'Thành viên',
  'vip.tier0': 'Cơ bản',
  'vip.tier1': 'Bạc',
  'vip.tier2': 'Vàng',
  'vip.tier3': 'Bạch kim',
  'vip.tier4': 'Kim cương',
  'vip.nextTier': 'Cấp tiếp theo',
  'vip.effectiveInvites': 'Lời mời hợp lệ',
  'vip.needMore': 'Thêm {{count}} lời mời để',
  'vip.maxLevel': 'Đã đạt cấp tối đa — mở khóa mọi quyền lợi',
  'vip.current': 'Hiện tại',
  'vip.allTiers': 'Tất cả cấp',
  'vip.benefits': 'Quyền lợi thành viên',
  'vip.b1': 'Thưởng mời bạn',
  'vip.b2': 'Ưu tiên xem xét',
  'vip.b3': 'Hỗ trợ VIP',
  'vip.b4': 'Rút tiền miễn phí',
  'vip.b1desc': 'Hệ số thưởng mời tăng theo cấp',
  'vip.b2desc': 'Vàng trở lên được ưu tiên xem xét',
  'vip.b3desc': 'Bạch kim trở lên có kênh hỗ trợ VIP',
  'vip.b4desc': 'Bạc trở lên được rút tiền miễn phí',
  'vip.currentTier': 'Cấp hiện tại',
  'vip.inviteCount': 'Số lời mời',
  'vip.tier5': 'Kim cương',
  'vip.upgradeTo': 'Nâng cấp lên',
  'vip.status': 'Trạng thái',
  'charts.earningsTrend': 'Xu hướng thu nhập',
  'charts.inviteGrowth': 'Tăng trưởng lời mời',
  'verify.title': 'Xác minh',
  'verify.howTo': 'Cách xác minh lời mời',
  'verify.step1': 'Sau khi bạn bè đăng ký, chụp màn hình cuộc trò chuyện hoặc trang thành công',
  'verify.step2': 'Chạm Tải ảnh lên trên người bạn để gửi bằng chứng',
  'verify.step3': 'Khi quản trị viên phê duyệt, lời mời được tính là hợp lệ',
  'verify.totalInvitees': 'Tổng',
  'verify.underReview': 'Đang xem xét',
  'verify.confirmed': 'Đã xác nhận',
  'verify.unverified': 'Chưa xác minh',
  'verify.inviteeList': 'Người tôi mời',
  'verify.upload': 'Tải lên',
  'verify.view': 'Xem',
  'verify.uploadTitle': 'Tải ảnh chụp mời bạn',
  'verify.uploadHint': 'Chọn người bạn bên dưới để tải bằng chứng',
  'verify.noInvitees': 'Chưa có người được mời. Hãy mời bạn bè trước!',
  'verify.releaseHere': 'Thả để tải lên',
  'verify.dropHere': 'Chạm để tải ảnh chụp mời bạn',
  'verify.dropHint': 'Hỗ trợ JPG, PNG, tối đa 10MB',
  'verify.uploadedList': 'Ảnh đã tải lên',
  'verify.uploaded': 'Đã tải ảnh chụp để xem xét',
  'verify.rejected': 'Đã từ chối',
  'support.q1': 'Làm thế nào để mời bạn bè?',
  'support.q2': 'Lời mời hợp lệ được tính thế nào?',
  'support.q3': 'Làm thế nào để nhận thưởng?',
  'support.q4': 'Làm thế nào để liên kết ví?',
  'support.q5': 'Xem xét mất bao lâu?',
  'support.q6': 'Làm thế nào để đổi mật khẩu?',
  'support.q7': 'Làm thế nào để nâng cấp?',
  'support.q8': 'Staking là gì?',
  'support.title': 'Bot hỗ trợ',
  'support.online': 'Trực tuyến · Tức thì',
  'support.welcome': 'Xin chào! Tôi là trợ lý hỗ trợ 🤖 Tôi có thể giúp gì? Chạm vào câu hỏi nhanh bên dưới hoặc nhập câu hỏi của bạn.',
  'support.notFound': 'Xin lỗi, tôi không tìm thấy câu trả lời. Thử từ khóa khác hoặc liên hệ Telegram @Shopping_Operations hoặc email support@shopee-ops.com',
  'support.placeholder': 'Nhập câu hỏi của bạn...',
  'support.faq': 'Câu hỏi thường gặp',
  'support.contactUs': 'Liên hệ chúng tôi',
  'support.chatTitle': 'Trò chuyện hỗ trợ',
  'support.typeMessage': 'Nhập tin nhắn của bạn...',
  'support.typing': 'Đang nhập...',
  'kyc.title': 'Xác minh danh tính',
  'kyc.unverified': 'Chưa xác minh',
  'kyc.pending': 'Đang xem xét',
  'kyc.verified': 'Đã xác minh',
  'kyc.unverifiedDesc': 'Hoàn tất xác minh để mở khóa mọi tính năng',
  'kyc.pendingDesc': 'Tài liệu của bạn đang được xem xét',
  'kyc.verifiedDesc': 'Đã hoàn tất xác minh danh tính',
  'kyc.submittedInfo': 'Thông tin đã gửi',
  'kyc.name': 'Tên',
  'kyc.idNumber': 'Số CMND/CCCD',
  'kyc.passportNumber': 'Số hộ chiếu',
  'kyc.licenseNumber': 'Số giấy phép',
  'kyc.frontImage': 'Mặt trước CMND',
  'kyc.backImage': 'Mặt sau CMND',
  'kyc.frontGeneric': 'Mặt trước tài liệu',
  'kyc.backGeneric': 'Mặt sau tài liệu',
  'kyc.passportFront': 'Trang thông tin hộ chiếu',
  'kyc.passportBack': 'Trang bìa hộ chiếu',
  'kyc.submitForm': 'Gửi xác minh',
  'kyc.docType': 'Loại tài liệu',
  'kyc.realName': 'Họ và tên',
  'kyc.idPlaceholder': 'Số CMND 18 ký tự',
  'kyc.passportPlaceholder': 'Số hộ chiếu',
  'kyc.licensePlaceholder': 'Số giấy phép',
  'kyc.uploadHint': 'Chạm để tải lên',
  'kyc.submitBtn': 'Gửi',
  'kyc.submitting': 'Đang gửi...',
  'kyc.privacy': 'Thông tin của bạn được mã hóa và bảo mật',
  'kyc.idCard': 'CMND/CCCD',
  'kyc.driverLicense': 'Giấy phép lái xe',
  'kyc.passport': 'Hộ chiếu',
  'kyc.uploadBoth': 'Tải cả hai mặt',
  'kyc.frontPhoto': 'Ảnh mặt trước',
  'kyc.backPhoto': 'Ảnh mặt sau',
  'kyc.uploadFront': 'Tải mặt trước',
  'kyc.uploadBack': 'Tải mặt sau',
  'kyc.submit': 'Gửi',
  'kyc.approved': 'Đã phê duyệt',
  'kyc.rejected': 'Đã từ chối',
  'kyc.approvedDesc': 'KYC đã được phê duyệt',
  'legal.title': 'Pháp lý & Thông tin',
  'legal.terms': 'Điều khoản dịch vụ',
  'legal.privacy': 'Chính sách bảo mật',
  'legal.liability': 'Tuyên bố miễn trừ trách nhiệm',
  'legal.about': 'Về chúng tôi',
  'legal.termsTitle': 'Điều khoản dịch vụ',
  'legal.version': 'Phiên bản',
  'legal.platform': 'Nền tảng',
  'legal.contact': 'Liên hệ',
  'legal.lastUpdated': 'Cập nhật lần cuối',
  'legal.disclaimer': 'Tuyên bố miễn trừ',
  'legal.termsBody': 'Nội dung điều khoản',
  'legal.privacyBody': 'Nội dung bảo mật',
  'legal.privacyTitle': 'Chính sách bảo mật',
  'legal.liabilityTitle': 'Tuyên bố miễn trừ trách nhiệm',
  'legal.aboutTitle': 'Về Shopee Shopping Operations',
  'sec.fillAll': 'Vui lòng điền đầy đủ',
  'sec.passLength': 'Tối thiểu 8 ký tự',
  'sec.passMismatch': 'Mật khẩu không khớp',
  'sec.passChanged': 'Đã đổi mật khẩu',
  'sec.enterPass': 'Nhập mật khẩu hiện tại',
  'sec.contactUpdated': 'Đã cập nhật liên hệ',
  'sec.title': 'Bảo mật',
  'sec.changePassword': 'Đổi mật khẩu',
  'sec.currentPassword': 'Mật khẩu hiện tại',
  'sec.newPassword': 'Mật khẩu mới',
  'sec.confirmNewPassword': 'Xác nhận mật khẩu mới',
  'sec.passUpdated': 'Đã cập nhật mật khẩu',
  'sec.changeContact': 'Đổi liên hệ',
  'sec.newEmail': 'Email mới',
  'sec.newPhone': 'Số điện thoại mới',
  'sec.currentInfo': 'Thông tin hiện tại',
  'security.title': 'Bảo mật',
  'security.subtitle': 'Đổi mật khẩu, cập nhật email & điện thoại',
  'security.currentInfo': 'Thông tin tài khoản hiện tại',
  'security.changePassword': 'Đổi mật khẩu',
  'security.changePasswordHint': 'Khuyến nghị cập nhật mật khẩu thường xuyên',
  'security.oldPassword': 'Mật khẩu hiện tại',
  'security.newPassword': 'Mật khẩu mới (tối thiểu 8 ký tự)',
  'security.confirmNewPassword': 'Xác nhận mật khẩu mới',
  'security.changeContact': 'Cập nhật Email / Điện thoại',
  'security.changeContactHint': 'Cập nhật thông tin liên hệ',
  'security.verifyPassword': 'Nhập mật khẩu hiện tại để xác minh',
  'security.enterCurrentPassword': 'Nhập mật khẩu hiện tại',
  'security.currentPassword': 'Mật khẩu hiện tại',
  'security.updatePassword': 'Cập nhật mật khẩu',
  'security.passwordUpdated': 'Đã cập nhật mật khẩu',
  'security.updateContact': 'Cập nhật liên hệ',
  'security.newEmail': 'Email mới',
  'security.newPhone': 'Điện thoại mới',
  'security.contactUpdated': 'Đã cập nhật liên hệ',
  'claim.submitOk': 'Đã gửi yêu cầu nhận thưởng',
  'claim.submitFail': 'Nhận thưởng thất bại',
  'claim.available': 'Phần thưởng có sẵn',
  'claim.pending': 'Đang xem xét',
  'claim.delivered': 'Đã nhận',
  'claim.effectiveCount': 'Lời mời hợp lệ',
  'claim.submittedAt': 'Đã gửi',
  'claim.withdrawn': 'Đã rút',
  'claim.withdrawnAt': 'Đã rút',
  'claim.arrivedAt': 'Đã nhận',
  'claim.confirmHint': 'Nhận thưởng này? Đã đạt ngưỡng {{count}} lời mời',
  'claim.willSendTo': 'Thưởng sẽ được gửi đến ví của bạn',
  'claim.noClaimable': 'Chưa có phần thưởng khả dụng',
  'claim.title': 'Tiêu đề',
  'claim.rejected': 'Đã từ chối',
  'claim.claimDetail': 'Chi tiết',
  'claim.noClaims': 'Chưa có yêu cầu nhận thưởng',
  'onboard.slide1Title': 'Chào mừng đến Shopee Shopping Operations',
  'onboard.slide1Body': 'Mời bạn bè, xây dựng số lời mời và nhận thưởng tiền mặt miễn phí',
  'onboard.slide2Title': 'Chia sẻ liên kết mời',
  'onboard.slide2Body': 'Sao chép mã giới thiệu hoặc mã QR và chia sẻ với bạn bè',
  'onboard.slide3Title': 'Đạt ngưỡng & Nhận thưởng',
  'onboard.slide3Body': 'Khi số lời mời đạt ngưỡng, nhận phần thưởng tiền mặt tương ứng',
  'onboard.slide4Title': 'Nhiều cấp = Kiếm nhiều hơn',
  'onboard.slide4Body': 'Khi bạn bè mời thêm người, bạn cũng nhận thưởng cấp 2 và cấp 3',
  'onboard.slide1Desc': 'Mời bạn bè, kiếm thưởng',
  'onboard.slide2Desc': 'Chia sẻ liên kết giới thiệu',
  'onboard.slide3Desc': 'Đạt ngưỡng, nhận thưởng',
  'onboard.slide4Desc': 'Thu nhập nhiều cấp',
  'onboard.skip': 'Bỏ qua',
  'onboard.getStarted': 'Bắt đầu',
  'onboard.next': 'Tiếp',
  'onboard.finish': 'Hoàn tất',
  'badges.title': 'Thành tựu',
  'badges.register': 'Người mới',
  'badges.first-invite': 'Người phá băng',
  'badges.invite-5': 'Người năng nổ',
  'badges.invite-15': 'Người mời chuyên nghiệp',
  'badges.invite-50': 'Bậc thầy mời',
  'badges.effective-10': 'Ngôi sao hiệu quả',
  'badges.effective-50': 'Cỗ máy tăng trưởng',
  'badges.level3': 'Ba thế hệ',
  'badges.first-claim': 'Thưởng đầu tiên',
  'badges.earn-100': 'Bách phu trưởng',
  'badges.firstInvite': 'Lời mời đầu tiên',
  'badges.invite5': '5 lời mời',
  'badges.invite15': '15 lời mời',
  'badges.invite50': '50 lời mời',
  'badges.effective10': '10 hợp lệ',
  'badges.effective50': '50 hợp lệ',
  'badges.firstClaim': 'Nhận thưởng đầu tiên',
  'badges.earn100': 'Kiếm $100',
  'common.darkMode': 'Chế độ tối',
  'common.darkModeHint': 'Chuyển giữa giao diện tối và sáng',
  'common.skip': 'Bỏ qua',
  'common.next': 'Tiếp',
  'common.start': 'Bắt đầu',
  'common.back': 'Quay lại',
  'common.language': 'Ngôn ngữ',
  'common.days': ' ngày',
  'common.people': '',
  'common.save': 'Lưu',
  'common.cancel': 'Hủy',
  'common.close': 'Đóng',
  'common.confirm': 'Xác nhận',
  'common.loadingFailed': 'Không thể tải dữ liệu',
  'common.operationFailed': 'Thao tác thất bại',
  'common.networkError': 'Lỗi mạng',
  'common.ok': 'OK',
  'common.copySuccess': 'Đã sao chép!',
  'common.submit': 'Đã gửi',
  'common.edit': 'Sửa',
  'common.delete': 'Xóa',
  'common.loading': 'Đang tải...',
  'common.noData': 'Không có dữ liệu',
  'common.search': 'Tìm kiếm',
  'common.filter': 'Lọc',
  'common.sort': 'Sắp xếp',
  'common.comingSoon': 'Sắp ra mắt',
  'store.title': 'Thương mại điện tử',
  'store.subtitle': 'Mở cửa hàng, chọn sản phẩm, bán kiếm lời',
  'store.all': 'Tất cả',
  'store.digital': 'Kỹ thuật số',
  'store.women': 'Nữ',
  'store.men': 'Nam',
  'store.beauty': 'Làm đẹp',
  'store.shoes': 'Giày dép',
  'store.home': 'Nhà cửa',
  'store.accessories': 'Phụ kiện',
  'store.food': 'Thực phẩm',
  'store.toys': 'Đồ chơi',
  'store.sports': 'Thể thao',
  'store.auto': 'Ô tô',
  'store.small': 'Cửa hàng nhỏ',
  'store.medium': 'Cửa hàng vừa',
  'store.large': 'Cửa hàng lớn',
  'store.premium': 'Cửa hàng cao cấp',
  'store.elite': 'Cửa hàng tinh hoa',
  'store.supreme': 'Cửa hàng tối thượng',
  'store.tierGuide': 'Cấp cửa hàng',
  'store.chooseTier': 'Chọn cấp cửa hàng',
  'store.addStore': 'Mở cửa hàng',
  'store.tierLevel': 'Cấp',
  'store.dailyMaxProfit': 'Tối đa/ngày',
  'store.payback': 'Hoàn vốn',
  'store.daysShort': 'ng',
  'store.deposit': 'Ký quỹ',
  'store.perOrder': 'Mỗi đơn',
  'store.dailyMax': 'Tối đa hàng ngày',
  'store.dailyOrders': '{{n}} đơn/ngày',
  'store.dailyOrdersShort': 'Hàng ngày',
  'store.openBtn': 'Mở cửa hàng (${{deposit}} ký quỹ)',
  'store.openSuccess': 'Đã mở cửa hàng!',
  'store.confirmClose': 'Đóng cửa hàng?',
  'store.noMatch': 'Không có sản phẩm phù hợp',
  'store.noProducts': 'Chưa có sản phẩm',
  'store.items': 'món',
  'store.dailyFull': 'Đã đầy hôm nay',
  'store.insufficient': 'Số dư không đủ',
  'store.buyNow': 'Mua ngay',
  'store.buy': 'Mua',
  'store.closeStore': 'Đóng',
  'store.closeConfirm': 'Đóng cửa hàng? Tiền ký quỹ sẽ được hoàn theo chính sách.',
  'store.todayProgress': 'Tiến độ hôm nay',
  'store.todayEarnings': 'Thu nhập hôm nay',
  'store.completed': 'Đã xong',
  'store.completedShort': 'Xong',
  'store.earned': 'Đã kiếm',
  'store.earnedShort': 'Đã kiếm',
  'store.remaining': 'còn lại',
  'store.processOrder': 'Xử lý đơn',
  'store.allDone': 'Đã hoàn tất mọi đơn hôm nay!',
  'store.howToProcess': 'Các bước xử lý đơn',
  'store.browse': 'Duyệt sản phẩm',
  'store.order': 'Đặt đơn',
  'store.review': 'Để lại đánh giá',
  'store.processing': 'Đang xử lý...',
  'store.orderDone': 'Đơn đã hoàn tất!',
  'store.rewardAdded': 'Đã ghi nhận thưởng',
  'store.openFree': 'Mở cửa hàng (ký quỹ $20)',
  'store.openDepositNote': 'Yêu cầu ký quỹ $20. Khóa trong 365 ngày, sau đó hoàn trả đầy đủ.',
  'store.depositRequired': 'Yêu cầu ký quỹ',
  'store.minDepositTopup': 'Nạp thêm ký quỹ để tiếp tục giao dịch.',
  'store.depositLocked': 'Ký quỹ đang khóa. Có thể nhận lại sau {{days}} ngày.',
  'store.depositLockedShort': 'Khóa {{days}} ngày',
  'store.withdrawDeposit': 'Rút ký quỹ',
  'store.refundDone': '${{amount}} đã hoàn về số dư',
  'store.closeDepositLocked': 'Đã đóng cửa hàng. Ký quỹ ${{amount}} vẫn khóa đến ngày đáo hạn.',
  'store.depositRefundable': 'Có thể nhận lại ngay',
  'store.dailyProfitReached': 'Đã đạt giới hạn lợi nhuận hàng ngày ({{cap}})',
  'store.capital': 'Vốn',
  'store.capitalFlow': 'Hoàn trả đầy đủ vốn sau khi hoàn tất + ghi nhận lợi nhuận',
  'store.tradeDone': 'Giao dịch hoàn tất',
  'store.closed': 'Đã đóng cửa hàng',
  'store.sold': 'đã bán',
  'store.limitedDeal': 'Ưu đãi có hạn',
  'store.marketPrice': 'Giá thị trường',
  'store.costPrice': 'Giá vốn',
  'store.earn': 'Kiếm',
  'store.sellEarn': 'Bán & Kiếm',
  'store.specs': 'Thông số',
  'store.description': 'Mô tả',
  'store.freeShipping': 'Miễn phí vận chuyển · Ghi nhận trong 7 ngày làm việc',
  'store.capitalGuarantee': 'Bảo đảm vốn · Hoàn 100%',
  'store.profitInstant': 'Lợi nhuận tức thì · Có thể rút',
  'store.todayProfit': 'Lợi nhuận hôm nay',
  'store.searchPlaceholder': 'Tìm sản phẩm...',
  'store.today': 'Hôm nay',
  'store.balance': 'Số dư',
  'store.withdraw': 'Rút tiền',
  'store.affordable': 'Giá phải chăng',
  'store.sortProfit': 'Lợi nhuận cao nhất',
  'store.sortPrice': 'Giá cao nhất',
  'store.sortSales': 'Nổi bật',
  'store.dailyGoal': 'Mục tiêu hàng ngày',
  'store.totalEarned': 'Tổng',
  'store.tomorrowEstimate': 'Ước tính ngày mai',
  'store.depositDesc': 'Khóa tiền làm tài sản thế chấp để mở khóa giao dịch giá trị cao hơn. Tỷ lệ 1:1 — ký quỹ $100 để giao dịch sản phẩm giá tới $100. Hoàn trả đầy đủ khi rút (không có khoản nắm giữ đang hoạt động).',
  'store.confirmDeposit': 'Xác nhận',
  'store.dashboard': 'Bảng điều khiển',
  'store.products': 'Sản phẩm',
  'store.orders': 'Đơn hàng',
  'store.profitTrend': 'Xu hướng lợi nhuận (7 ngày)',
  'store.topProducts': 'Kiếm nhiều nhất',
  'store.noOrders': 'Chưa có đơn',
  'store.orderLabel': 'Đơn',
  'store.metrics': 'Chỉ số',
  'store.profitRate': 'Tỷ lệ lợi nhuận',
  'store.tier': 'Cấp cửa hàng',
  'store.week': 'Tuần',
  'store.month': 'Tháng',
  'store.total': 'Tổng',
  'store.depositSuccess': 'Đã nạp!',
  'store.holdingMode': 'Nắm giữ',
  'store.shareMode': 'Chia sẻ',
  'store.share': 'Chia sẻ',
  'store.shareEarn': 'Chia sẻ & Kiếm',
  'store.need': 'Cần',
  'store.have': 'Khả dụng',
  'store.shortage': 'Thiếu',
  'store.howToEarn': 'Cách nhận tiền',
  'store.tipCheckin': 'Điểm danh hàng ngày: $0.10-$0.70',
  'store.tipHolding': 'Khoản nắm giữ tự bán và hoàn tiền',
  'store.holdings': 'Khoản nắm giữ của tôi',
  'store.noHoldings': 'Không có khoản nắm giữ đang hoạt động',
  'store.totalReturn': 'Tổng hoàn lại',
  'store.shareCommission': 'Hoa hồng',
  'store.shareRate': 'của giá mua',
  'store.shareHint': 'Chia sẻ liên kết này. Khi có người mua, bạn nhận hoa hồng.',
  'store.dailyLimitReached': 'Đã đạt giới hạn hàng ngày',
  'store.dailyLimitMsg': 'Bạn đã hoàn tất mọi đơn hôm nay. Hãy quay lại vào ngày mai!',
  'store.gotIt': 'Đã hiểu',
  'store.depositMinMax': 'Tối thiểu $1 · Tối đa $10,000',
  'store.bellHint': 'Thông báo',
  'store.costPriceColon': 'Giá vốn:',
  'store.sellBy': 'Bán trước',
  'store.boughtMsg': 'Đã mua! Dự kiến bán trước',
  'store.shareGenerated': 'Đã tạo liên kết chia sẻ!',
  'store.shareFailed': 'Chia sẻ thất bại',
  'store.linkCopiedMsg': 'Đã sao chép liên kết! Chia sẻ với bạn bè.',
  'store.itemsSold': '{{n}} món đã bán!',
  'store.depositShortage': 'Cần thêm ký quỹ để giao dịch món này',
  'store.maxTrade': 'Giao dịch tối đa',
  'store.addDeposit': '+Nạp',
  'store.freeOrders': 'Miễn phí',
  'notifications.title': 'Thông báo',
  'notifications.markAllRead': 'Đánh dấu đã đọc tất cả',
  'notifications.empty': 'Không có thông báo',
};

// specs 商品规格参数（越南语）
const specsVi = {
  '产地': 'Xuất xứ', '亮度': 'Độ sáng', '件数': 'Số lượng', '传感器': 'Cảm biến',
  '保修': 'Bảo hành', '保养': 'Bảo quản', '保护': 'Bảo vệ', '光圈': 'Khẩu độ',
  '兼容': 'Tương thích', '内存': 'RAM', '内容': 'Nội dung', '刀片': 'Lưỡi dao',
  '分辨率': 'Độ phân giải', '功率': 'Công suất', '功能': 'Chức năng', '包含': 'Bao gồm',
  '卡口': 'Ngàm', '参数': 'Thông số', '吸力': 'Lực hút', '品牌': 'Thương hiệu',
  '品质': 'Chất lượng', '地毯': 'Thảm', '型号': 'Mẫu mã', '处理器': 'Bộ xử lý',
  '天线': 'Ăng-ten', '存储': 'Bộ nhớ', '安全': 'An toàn', '安装': 'Lắp đặt',
  '定位': 'Định vị', '容量': 'Dung lượng', '密封': 'Niêm phong', '对焦': 'Lấy nét',
  '导航': 'Điều hướng', '尺寸': 'Kích thước', '屏幕': 'Màn hình', '平台': 'Nền tảng',
  '感应': 'Cảm biến', '手柄': 'Tay cầm', '技术': 'Công nghệ', '探测': 'Phát hiện',
  '接口': 'Cổng kết nối', '接收': 'Thu tín hiệu', '控制': 'Điều khiển', '摄像头': 'Camera',
  '散热': 'Tản nhiệt', '数量': 'Số lượng', '显卡': 'GPU', '显存': 'VRAM',
  '显示': 'Hiển thị', '材质': 'Chất liệu', '档位': 'Cấp độ', '水箱': 'Bình nước',
  '涂层': 'Lớp phủ', '清洁': 'Vệ sinh', '清洗': 'Máy rửa bát', '温度': 'Nhiệt độ',
  '温控': 'Kiểm soát nhiệt', '灵敏度': 'Độ nhạy', '特色': 'Tính năng', '电压': 'Điện áp',
  '电池': 'Pin', '直播': 'Livestream', '箭头': 'Mũi tên', '类型': 'Loại',
  '系统': 'Hệ điều hành', '续航': 'Thời lượng pin', '网络': 'Mạng', '翻转': 'Xoay',
  '耐热': 'Chịu nhiệt', '肥皂': 'Xà phòng', '自动集尘': 'Tự đổ bụi', '自清洁': 'Tự làm sạch',
  '色彩': 'Độ sâu màu', '芯片': 'Chip', '菜单': 'Menu', '蒸汽': 'Hơi nước',
  '视频': 'Video', '警报': 'Cảnh báo', '越障': 'Vượt chướng ngại vật', '转向': 'Đánh lái',
  '输出': 'Đầu ra', '运动': 'Thể thao', '连拍': 'Chụp liên tiếp', '连接': 'Kết nối',
  '适用': 'Tương thích', '通道': 'Kênh', '重量': 'Trọng lượng', '锁定': 'Khóa',
  '长度': 'Chiều dài', '防抖': 'Chống rung', '防水': 'Chống nước', '防缠绕': 'Chống rối',
  '附件': 'Phụ kiện', '除味': 'Khử mùi', '集尘袋': 'Túi bụi', '音频': 'Âm thanh',
  '频率': 'Tần số', '颜色': 'Màu sắc', '香味': 'Hương thơm', 'AI': 'AI',
  'App': 'App', 'GPS': 'GPS', 'HDR': 'HDR',
};

// legal 长文本（越南语，简洁版）
const legalVi = {
  'legal.termsContent.0.title': '1. Chấp nhận điều khoản',
  'legal.termsContent.0.body': 'Bằng cách truy cập hoặc sử dụng Shopee Shopping Operations ("Nền tảng"), bạn xác nhận đã đọc, hiểu và đồng ý chịu ràng buộc bởi các Điều khoản dịch vụ này. Nếu không đồng ý, bạn không được sử dụng Nền tảng. Các điều khoản này tạo thành thỏa thuận ràng buộc pháp lý giữa bạn và nhà vận hành Nền tảng.',
  'legal.termsContent.1.title': '2. Điều kiện & Đăng ký tài khoản',
  'legal.termsContent.1.body': 'Bạn phải từ 18 tuổi trở lên để sử dụng Nền tảng. Khi đăng ký, bạn đồng ý cung cấp thông tin chính xác và đầy đủ bao gồm email và số điện thoại hợp lệ. Mỗi cá nhân chỉ được dùng một tài khoản. Bạn chịu trách nhiệm bảo mật thông tin đăng nhập và mọi hoạt động trong tài khoản của mình.',
  'legal.termsContent.2.title': '3. Dịch vụ của Nền tảng',
  'legal.termsContent.2.body': 'Nền tảng kết nối người dùng với đối tác thương mại điện tử, cho phép thành viên kiếm thu nhập bằng cách hoàn thành nhiệm vụ mua sắm. Người dùng cũng có thể kiếm hoa hồng qua chương trình giới thiệu nhiều cấp. Mọi khoản thu nhập đều phải xác minh; Nền tảng có quyền điều chỉnh hoặc giữ lại thưởng khi nghi ngờ gian lận.',
  'legal.termsContent.3.title': '4. Hệ thống giới thiệu & hoa hồng',
  'legal.termsContent.3.body': 'Nền tảng vận hành chương trình giới thiệu 3 cấp: Cấp 1 (giới thiệu trực tiếp): 1.0%; Cấp 2: 0.5%; Cấp 3: 0.25%. Tỷ lệ có thể điều chỉnh theo quyết định của Nền tảng với thông báo trước. Hoa hồng chỉ được ghi nhận sau khi xác minh thành công.',
  'legal.termsContent.4.title': '5. KYC & Xác minh danh tính',
  'legal.termsContent.4.body': 'Để rút tiền và nâng hạn mức giao dịch, bạn phải hoàn tất xác minh danh tính (KYC) bằng giấy tờ do chính phủ cấp hợp lệ. Bạn cam kết mọi tài liệu gửi đều là thật và thuộc về bạn. Nộp tài liệu giả mạo sẽ bị khóa tài khoản vĩnh viễn và mất toàn bộ tiền.',
  'legal.termsContent.5.title': '6. Nạp tiền, rút tiền & thanh toán',
  'legal.termsContent.5.body': 'Nạp tiền được xử lý qua các mạng thanh toán được hỗ trợ. Rút tiền yêu cầu hoàn tất KYC và tuân theo hạn mức tối thiểu cùng thời gian xử lý. Nền tảng không chịu trách nhiệm về sự chậm trễ do bên thứ ba gây ra.',
  'legal.termsContent.6.title': '7. Hoạt động bị cấm',
  'legal.termsContent.6.body': 'Nghiêm cấm: dùng script tự động, bot; tạo nhiều tài khoản giả; nộp bằng chứng xác minh giả; tham gia gian lận hoàn tiền; quấy rối hoặc lừa dối người dùng khác; tấn công hệ thống; và mọi hoạt động vi phạm pháp luật.',
  'legal.termsContent.7.title': '8. Sở hữu trí tuệ',
  'legal.termsContent.7.body': 'Mọi nội dung trên Nền tảng đều là tài sản độc quyền của Nền tảng hoặc bên cấp phép và được bảo vệ bởi luật sở hữu trí tuệ. Bạn không được sao chép, phân phối hoặc tạo tác phẩm phái sinh khi chưa có sự cho phép bằng văn bản.',
  'legal.termsContent.8.title': '9. Giới hạn trách nhiệm',
  'legal.termsContent.8.body': 'Trong phạm vi pháp luật cho phép, Nền tảng không chịu trách nhiệm về thiệt hại gián tiếp, ngẫu nhiên, đặc biệt hoặc mang tính trừng phạt phát sinh từ việc sử dụng hoặc không thể sử dụng Nền tảng.',
  'legal.termsContent.9.title': '10. Sửa đổi & cập nhật',
  'legal.termsContent.9.body': 'Chúng tôi có quyền sửa đổi các điều khoản này bất cứ lúc nào. Thay đổi quan trọng sẽ được thông báo qua hệ thống hoặc email. Việc tiếp tục sử dụng sau khi sửa đổi có hiệu lực đồng nghĩa với chấp nhận điều khoản mới.',
  'legal.termsContent.10.title': '11. Chấm dứt',
  'legal.termsContent.10.body': 'Bạn có thể chấm dứt tài khoản bất cứ lúc nào bằng cách liên hệ hỗ trợ. Khi chấm dứt, thu nhập đã xác minh sẽ được thanh toán trong 30 ngày làm việc, tuân theo phí và hạn mức áp dụng.',
  'legal.termsContent.11.title': '12. Luật điều chỉnh & giải quyết tranh chấp',
  'legal.termsContent.11.body': 'Các điều khoản này được điều chỉnh theo pháp luật hiện hành. Tranh chấp trước tiên được giải quyết bằng thương lượng thiện chí; nếu thất bại, sẽ được đưa ra trọng tài ràng buộc theo quy tắc của cơ quan trọng tài liên quan.',
  'legal.privacyContent.0.title': '1. Thông tin chúng tôi thu thập',
  'legal.privacyContent.0.body': 'Chúng tôi thu thập: thông tin tài khoản (email, điện thoại, tên); dữ liệu xác minh (giấy tờ tùy thân, ảnh selfie); dữ liệu giao dịch (nạp, rút, lịch sử nhiệm vụ, hoa hồng, địa chỉ ví); dữ liệu giới thiệu; dữ liệu kỹ thuật (IP, trình duyệt, thiết bị, thời gian truy cập).',
  'legal.privacyContent.1.title': '2. Cách chúng tôi sử dụng thông tin',
  'legal.privacyContent.1.body': 'Thông tin của bạn chỉ được dùng để: xác minh danh tính và chống gian lận; xử lý nạp, rút và thanh toán hoa hồng; duy trì tài khoản và hỗ trợ; theo dõi giới thiệu; cải thiện tính năng; gửi thông báo liên quan dịch vụ; và tuân thủ pháp luật.',
  'legal.privacyContent.2.title': '3. Lưu trữ & bảo mật dữ liệu',
  'legal.privacyContent.2.body': 'Chúng tôi dùng các biện pháp bảo mật tiêu chuẩn ngành: mã hóa truyền tải TLS 1.3, mã hóa dữ liệu AES-256, băm mật khẩu bcrypt, kiểm tra bảo mật định kỳ và kiểm soát truy cập nghiêm ngặt.',
  'legal.privacyContent.3.title': '4. Chia sẻ & tiết lộ dữ liệu',
  'legal.privacyContent.3.body': 'Chúng tôi không bán hoặc trao đổi thông tin cá nhân của bạn. Chúng tôi chỉ chia sẻ với nhà cung cấp dịch vụ theo thỏa thuận bảo mật nghiêm ngặt, khi pháp luật yêu cầu, hoặc để bảo vệ quyền và an toàn.',
  'legal.privacyContent.4.title': '5. Lưu giữ dữ liệu',
  'legal.privacyContent.4.body': 'Chúng tôi chỉ lưu dữ liệu khi cần thiết. Dữ liệu tài khoản được giữ khi tài khoản hoạt động và 90 ngày sau khi đóng. Hồ sơ giao dịch có thể giữ tới 7 năm. Tài liệu KYC giữ theo yêu cầu chống rửa tiền.',
  'legal.privacyContent.5.title': '6. Quyền & lựa chọn của bạn',
  'legal.privacyContent.5.body': 'Tùy khu vực pháp lý, bạn có quyền truy cập, sửa, xóa, hạn chế xử lý dữ liệu, quyền di chuyển dữ liệu và rút lại đồng ý. Liên hệ Telegram @Shopping_Operations để thực hiện quyền; chúng tôi phản hồi trong 30 ngày.',
  'legal.privacyContent.6.title': '7. Cookie & công nghệ theo dõi',
  'legal.privacyContent.6.body': 'Chúng tôi dùng cookie thiết yếu cho phiên đăng nhập, xác thực và bảo mật. Chúng tôi không dùng cookie quảng cáo bên thứ ba.',
  'legal.privacyContent.7.title': '8. Chuyển dữ liệu quốc tế',
  'legal.privacyContent.7.body': 'Dữ liệu của bạn có thể được lưu và xử lý ở nước ngoài. Chúng tôi đảm bảo có biện pháp bảo vệ phù hợp khi chuyển dữ liệu quốc tế.',
  'legal.privacyContent.8.title': '9. Quyền riêng tư của trẻ em',
  'legal.privacyContent.8.body': 'Nền tảng không dành cho người dưới 18 tuổi. Chúng tôi không cố ý thu thập thông tin từ trẻ vị thành niên.',
  'legal.privacyContent.9.title': '10. Liên hệ & khiếu nại',
  'legal.privacyContent.9.body': 'Với mọi thắc mắc về quyền riêng tư, liên hệ Telegram @Shopping_Operations. Bạn cũng có quyền khiếu nại với cơ quan bảo vệ dữ liệu địa phương.',
  'legal.liabilityContent.0.title': '1. Bản chất dịch vụ',
  'legal.liabilityContent.0.body': 'Shopee Shopping Operations là nền tảng kiếm tiền theo nhiệm vụ. Chúng tôi không phải tổ chức tài chính, cố vấn đầu tư, môi giới chứng khoán hay đơn vị chuyển tiền được cấp phép.',
  'legal.liabilityContent.1.title': '2. Không tư vấn tài chính',
  'legal.liabilityContent.1.body': 'Không nội dung nào trên Nền tảng là tư vấn tài chính, đầu tư, pháp lý hay thuế. Bạn nên tham khảo chuyên gia trước khi ra quyết định tài chính.',
  'legal.liabilityContent.2.title': '3. Tuyên bố về thu nhập',
  'legal.liabilityContent.2.body': 'Mọi ví dụ hoặc ước tính thu nhập chỉ mang tính minh họa, không đảm bảo thu nhập thực tế. Kết quả thực tế phụ thuộc nhiều yếu tố.',
  'legal.liabilityContent.3.title': '4. Dịch vụ & liên kết bên thứ ba',
  'legal.liabilityContent.3.body': 'Nền tảng tích hợp với các nền tảng thương mại điện tử, bộ xử lý thanh toán và mạng blockchain bên thứ ba. Chúng tôi không đảm bảo tính khả dụng hay bảo mật của dịch vụ bên thứ ba.',
  'legal.liabilityContent.4.title': '5. Bất khả kháng',
  'legal.liabilityContent.4.body': 'Nền tảng không chịu trách nhiệm về thất bại hoặc chậm trễ do thiên tai, chiến tranh, khủng bố, hành động chính phủ, tấn công mạng, sự cố viễn thông, mất điện và đại dịch.',
  'legal.liabilityContent.5.title': '6. Bồi thường',
  'legal.liabilityContent.5.body': 'Bạn đồng ý bồi thường và giữ Nền tảng vô can trước mọi khiếu nại, thiệt hại và chi phí phát sinh từ việc bạn vi phạm điều khoản, sử dụng Nền tảng, vi phạm quyền bên thứ ba hoặc hoạt động gian lận.',
  'legal.liabilityContent.6.title': '7. Tuyên bố miễn trừ bảo đảm',
  'legal.liabilityContent.6.body': 'Nền tảng được cung cấp "nguyên trạng" và "khi có sẵn", không có bất kỳ bảo đảm nào, dù rõ ràng hay ngụ ý.',
  'legal.liabilityContent.7.title': '8. Tính tách rời',
  'legal.liabilityContent.7.body': 'Nếu bất kỳ điều khoản nào bị tuyên bố vô hiệu, điều khoản đó sẽ được tách rời và các điều khoản còn lại vẫn có hiệu lực.',
  'legal.aboutContent.0.title': 'Chúng tôi làm gì',
  'legal.aboutContent.0.body': 'Shopee Shopping Operations là nền tảng kiếm tiền theo nhiệm vụ, kết nối nhà bán hàng thương mại điện tử với mạng lưới người dùng. Thành viên kiếm thu nhập thật bằng cách hoàn thành nhiệm vụ mua sắm đã xác minh và mời người khác tham gia.',
  'legal.aboutContent.1.title': 'Cách hoạt động',
  'legal.aboutContent.1.body': '1. Duyệt nhiệm vụ mua sắm trong Cửa hàng. 2. Hoàn tất mua hàng trên nền tảng đối tác. 3. Nhận lợi nhuận sau khi xác minh. 4. Mở rộng thu nhập bằng cách mời bạn bè. 5. Rút tiền sau khi hoàn tất KYC.',
  'legal.aboutContent.2.title': 'Sứ mệnh của chúng tôi',
  'legal.aboutContent.2.body': 'Chúng tôi tin rằng thời gian và mạng lưới của mỗi người đều có giá trị. Sứ mệnh của chúng tôi là tạo cơ hội kiếm tiền dễ tiếp cận bằng cách kết nối người tiêu dùng với nền kinh tế thương mại điện tử toàn cầu.',
  'legal.aboutContent.3.title': 'Giá trị cốt lõi',
  'legal.aboutContent.3.body': 'Minh bạch: mô tả nhiệm vụ rõ ràng, theo dõi thu nhập thời gian thực. Chính trực: chống gian lận nghiêm ngặt, xác minh nhiệm vụ, quy trình xem xét công bằng. Cộng đồng: cùng nhau phát triển. Đổi mới: liên tục cải tiến nền tảng.',
  'legal.aboutContent.4.title': 'Đội ngũ của chúng tôi',
  'legal.aboutContent.4.body': 'Chúng tôi là đội ngũ phân tán gồm chuyên gia thương mại điện tử, kỹ sư phần mềm và nhà vận hành cộng đồng.',
  'legal.aboutContent.5.title': 'Liên hệ & hợp tác',
  'legal.aboutContent.5.body': 'Với câu hỏi, hỗ trợ hoặc hợp tác, liên hệ Telegram: @Shopping_Operations. Chúng tôi phản hồi trong 24 giờ.',
  'legal.aboutContent.6.title': 'Thống kê nền tảng',
  'legal.aboutContent.6.body': 'Chúng tôi duy trì quy trình xác minh nghiêm ngặt để đảm bảo tính toàn vẹn của nền tảng. Mọi nhiệm vụ được xem xét trước khi thanh toán, mọi lời mời được xác thực.',
};

// 合并所有翻译（普通 key + specs + legal）
const specsWithPrefix = {};
for (const k of Object.keys(specsVi)) specsWithPrefix['specs.' + k] = specsVi[k];
const all = { ...vi, ...specsWithPrefix, ...legalVi };

// 生成 vi.json：遍历 en.json，对每个 key 用翻译（缺的 fallback 英文）
function build(obj, prefix = '') {
  const out = {};
  for (const k of Object.keys(obj)) {
    const key = prefix ? prefix + '.' + k : k;
    if (typeof obj[k] === 'object' && obj[k] !== null && !Array.isArray(obj[k])) {
      out[k] = build(obj[k], key);
    } else {
      out[k] = all[key] !== undefined ? all[key] : obj[k];
    }
  }
  return out;
}

const viJson = build(en);
const outPath = path.join(__dirname, '..', 'client', 'src', 'i18n', 'locales', 'vi.json');
fs.writeFileSync(outPath, JSON.stringify(viJson, null, 2) + '\n', 'utf8');

// 校验 key 对齐
function allKeys(obj, prefix = '') {
  const keys = [];
  for (const k of Object.keys(obj)) {
    const full = prefix ? prefix + '.' + k : k;
    if (typeof obj[k] === 'object' && obj[k] !== null) keys.push(...allKeys(obj[k], full));
    else keys.push(full);
  }
  return keys;
}
const enKeys = new Set(allKeys(en));
const viKeys = allKeys(viJson);
const missing = viKeys.filter(k => !enKeys.has(k));
const extra = [...enKeys].filter(k => !viKeys.includes(k));
console.log('en keys:', enKeys.size, '| vi keys:', viKeys.length);
console.log('vi 缺失 key:', missing.length, '| vi 多余 key:', extra.length);
if (missing.length) console.log('缺失示例:', missing.slice(0, 5));
if (extra.length) console.log('多余示例:', extra.slice(0, 5));
console.log('vi.json 已生成:', outPath);
